# Using Machine Learning techniques to predict a stroke

## Imports

In [341]:
import kagglehub
import os
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, classification_report
from sklearn.base import clone
from tensorflow.keras.models import Sequential, clone_model
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

## Load in data, basic data information

In [342]:
path = kagglehub.dataset_download("fedesoriano/stroke-prediction-dataset")

file_path = os.path.join(path, "healthcare-dataset-stroke-data.csv")
df = pd.read_csv(file_path)

df.head()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [343]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   str
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   str
 6   work_type          5110 non-null   str
 7   Residence_type     5110 non-null   str
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   str
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), str(5)
memory usage: 479.2 KB

## Data cleaning

In [344]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='str')

### Checking data for unique values

Before modifying the data to be fit for training we should check how many unique values each feature can have, so that we can determine how to represent it (eg. use 0 and 1 for yes-no columns or one-hot encoding for those with more posiible values).

In [345]:
for column in df.columns:
    print(f"{column} values: {df[column].unique()}")

id values: [ 9046 51676 31112 ... 19723 37544 44679]
gender values: <StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str
age values: [6.70e+01 6.10e+01 8.00e+01 4.90e+01 7.90e+01 8.10e+01 7.40e+01 6.90e+01
 5.90e+01 7.80e+01 5.40e+01 5.00e+01 6.40e+01 7.50e+01 6.00e+01 5.70e+01
 7.10e+01 5.20e+01 8.20e+01 6.50e+01 5.80e+01 4.20e+01 4.80e+01 7.20e+01
 6.30e+01 7.60e+01 3.90e+01 7.70e+01 7.30e+01 5.60e+01 4.50e+01 7.00e+01
 6.60e+01 5.10e+01 4.30e+01 6.80e+01 4.70e+01 5.30e+01 3.80e+01 5.50e+01
 1.32e+00 4.60e+01 3.20e+01 1.40e+01 3.00e+00 8.00e+00 3.70e+01 4.00e+01
 3.50e+01 2.00e+01 4.40e+01 2.50e+01 2.70e+01 2.30e+01 1.70e+01 1.30e+01
 4.00e+00 1.60e+01 2.20e+01 3.00e+01 2.90e+01 1.10e+01 2.10e+01 1.80e+01
 3.30e+01 2.40e+01 3.40e+01 3.60e+01 6.40e-01 4.10e+01 8.80e-01 5.00e+00
 2.60e+01 3.10e+01 7.00e+00 1.20e+01 6.20e+01 2.00e+00 9.00e+00 1.50e+01
 2.80e+01 1.00e+01 1.80e+00 3.20e-01 1.08e+00 1.90e+01 6.00e+00 1.16e+00
 1.00e+00 1.40e+00 1.72e+00 2.40e-01 1.64e+00 1.56e+00 7.20e-01 1.88e+00
 1.24e+00 8.00e-01 4.00e-01 8.00e-02 1.48e+00 5.60e-01 4.80e-01 1.60e-01]
hypertension values: [0 1]
heart_disease values: [1 0]
ever_married values: <StringArray>
['Yes', 'No']
Length: 2, dtype: str
work_type values: <StringArray>
['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked']
Length: 5, dtype: str
Residence_type values: <StringArray>
['Urban', 'Rural']
Length: 2, dtype: str
avg_glucose_level values: [228.69 202.21 105.92 ...  82.99 166.29  85.28]
bmi values: [36.6  nan 32.5 34.4 24.  29.  27.4 22.8 24.2 29.7 36.8 27.3 28.2 30.9
 37.5 25.8 37.8 22.4 48.9 26.6 27.2 23.5 28.3 44.2 25.4 22.2 30.5 26.5
 33.7 23.1 32.  29.9 23.9 28.5 26.4 20.2 33.6 38.6 39.2 27.7 31.4 36.5
 33.2 32.8 40.4 25.3 30.2 47.5 20.3 30.  28.9 28.1 31.1 21.7 27.  24.1
 45.9 44.1 22.9 29.1 32.3 41.1 25.6 29.8 26.3 26.2 29.4 24.4 28.  28.8
 34.6 19.4 30.3 41.5 22.6 56.6 27.1 31.3 31.  31.7 35.8 28.4 20.1 26.7
 38.7 34.9 25.  23.8 21.8 27.5 24.6 32.9 26.1 31.9 34.1 36.9 37.3 45.7
 34.2 23.6 22.3 37.1 45.  25.5 30.8 37.4 34.5 27.9 29.5 46.  42.5 35.5
 26.9 45.5 31.5 33.  23.4 30.7 20.5 21.5 40.  28.6 42.2 29.6 35.4 16.9
 26.8 39.3 32.6 35.9 21.2 42.4 40.5 36.7 29.3 19.6 18.  17.6 19.1 50.1
 17.7 54.6 35.  22.  39.4 19.7 22.5 25.2 41.8 60.9 23.7 24.5 31.2 16.
 31.6 25.1 24.8 18.3 20.  19.5 36.  35.3 40.1 43.1 21.4 34.3 27.6 16.5
 24.3 25.7 21.9 38.4 25.9 54.7 18.6 24.9 48.2 20.7 39.5 23.3 64.8 35.1
 43.6 21.  47.3 16.6 21.6 15.5 35.6 16.7 41.9 16.4 17.1 29.2 37.9 44.6
 39.6 40.3 41.6 39.  23.2 18.9 36.1 36.3 46.5 16.8 46.6 35.2 20.9 13.8
 31.8 15.3 38.2 45.2 17.  49.8 27.8 60.2 23.  22.1 26.  44.3 51.  39.7
 34.7 21.3 41.2 34.8 19.2 35.7 40.8 24.7 19.  32.4 34.  28.7 32.1 51.5
 20.4 30.6 71.9 19.3 40.9 17.2 16.1 16.2 40.6 18.4 21.1 42.3 32.2 50.2
 17.5 18.7 42.1 47.8 20.8 30.1 17.3 36.4 12.  36.2 55.7 14.4 43.  41.7
 33.8 43.9 22.7 57.5 37.  38.5 16.3 44.  32.7 54.2 40.2 33.3 17.4 41.3
 52.3 14.6 17.8 46.1 33.1 18.1 43.8 50.3 38.9 43.7 39.9 15.9 19.8 12.3
 78.  38.3 41.  42.6 43.4 15.1 20.6 33.5 43.2 30.4 38.  33.4 44.9 44.7
 37.6 39.8 53.4 55.2 42.  37.2 42.8 18.8 42.9 14.3 37.7 48.4 50.6 46.2
 49.5 43.3 33.9 18.5 44.5 45.4 55.  54.8 19.9 17.9 15.6 52.8 15.2 66.8
 55.1 18.2 48.5 55.9 57.3 10.3 14.1 15.7 56.  44.8 13.4 51.8 38.1 57.7
 44.4 38.8 49.3 39.1 54.  56.1 97.6 53.9 13.7 11.5 41.4 14.2 49.4 15.4
 45.1 49.2 48.7 53.8 42.7 48.8 52.7 53.5 50.5 15.8 45.3 14.8 51.9 63.3
 40.7 61.2 48.  46.8 48.3 58.1 50.4 11.3 12.8 13.5 14.5 15.  59.7 47.4
 52.5 13.2 52.9 61.6 49.9 54.3 47.9 13.  13.9 50.9 57.2 64.4 92.  50.8
 57.9 45.8 47.6 14.  46.4 46.9 47.1 13.3 48.1 51.7 46.3 54.1 14.9]
smoking_status values: <StringArray>
['formerly smoked', 'never smoked', 'smokes', 'Unknown']
Length: 4, dtype: str
stroke values: [1 0]

### Adjusting column types

In [346]:
df["age"] = df["age"].astype("uint8")
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

### Checking for NaN values

We check if there are any values missing from the dataset.
- `df.isna()` – returns a DataFrame of True/False values (True if the value in the original DataFrame is NaN, False otherwise)  
- `df.isna().any()` – for each column, checks if it contains at least one True value  
- `df.isna().any().any()` – returns True if there is **at least one NaN** in the original DataFrame, False otherwise

In [347]:
df.isna().any().any()

np.True_

### Dealing with NaNs

BMI is the only columns with missing values. We fill them using the gender average.

In [348]:
df["bmi"] = df["bmi"].fillna(df.groupby("gender")["bmi"].transform("mean"))
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,51676,Female,61,0,0,Yes,Self-employed,Rural,202.21,29.065758,never smoked,1
2,31112,Male,80,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,60182,Female,49,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,1665,Female,79,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80,1,0,Yes,Private,Urban,83.75,29.065758,never smoked,0
5106,44873,Female,81,0,0,Yes,Self-employed,Urban,125.20,40.000000,never smoked,0
5107,19723,Female,35,0,0,Yes,Self-employed,Rural,82.99,30.600000,never smoked,0
5108,37544,Male,51,0,0,Yes,Private,Rural,166.29,25.600000,formerly smoked,0
5109,44679,Female,44,0,0,Yes,Govt_job,Urban,85.28,26.200000,Unknown,0

### Modifying the data

In [349]:
# Binary to 1/0
df["ever_married"] = df["ever_married"].map({"Yes": 1, "No": 0})

# One-Hot Encoding
df = pd.get_dummies(df, columns=["gender", "work_type", "Residence_type", "smoking_status"])

# Convert all bool columns from OHE to int
bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)

df.head()

,id,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,...,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,9046,67,0,1,1,228.69,36.600000,1,0,1,...,0,1,0,0,0,1,0,1,0,0
1,51676,61,0,0,1,202.21,29.065758,1,1,0,...,0,0,1,0,1,0,0,0,1,0
2,31112,80,0,1,1,105.92,32.500000,1,0,1,...,0,1,0,0,1,0,0,0,1,0
3,60182,49,0,0,1,171.23,34.400000,1,1,0,...,0,1,0,0,0,1,0,0,0,1
4,1665,79,1,0,1,174.12,24.000000,1,1,0,...,0,0,1,0,1,0,0,0,1,0

In [350]:
# Move label to the rightmost side of the dataframe
cols = [c for c in df.columns if c != "stroke"] + ["stroke"]
df = df[cols]

### Renaming the columns

In this step we standardize the naming convention of features in the dataframe.

In [351]:
def get_renamed_column(name):
    name = name.strip()
    name = name.lower()
    name = name.replace(" ", "_")

    return name


def get_rename_dict(column_names):
    rename_dict = {}
    for name in column_names:
        rename_dict[name] = get_renamed_column(name)

    return rename_dict

In [352]:
df = df.rename(columns=get_rename_dict(df.columns))
df.head()

,id,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,gender_female,gender_male,gender_other,...,work_type_private,work_type_self-employed,work_type_children,residence_type_rural,residence_type_urban,smoking_status_unknown,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes,stroke
0,9046,67,0,1,1,228.69,36.600000,0,1,0,...,1,0,0,0,1,0,1,0,0,1
1,51676,61,0,0,1,202.21,29.065758,1,0,0,...,0,1,0,1,0,0,0,1,0,1
2,31112,80,0,1,1,105.92,32.500000,0,1,0,...,1,0,0,1,0,0,0,1,0,1
3,60182,49,0,0,1,171.23,34.400000,1,0,0,...,1,0,0,0,1,0,0,0,1,1
4,1665,79,1,0,1,174.12,24.000000,1,0,0,...,0,1,0,1,0,0,0,1,0,1

### Check for duplicates

In [353]:
any(df.duplicated())

False

There are only unique records in the dataset already, we may proceed.

### Check for class imbalance

Ideally here should be a similar number of records in each class.

In [354]:
df[df.columns[-1]].sum() / df[df.columns[-1]].size

np.float64(0.0487279843444227)

Since stroke was confirmed only in 5% of patients we will use a few different techniques deal with the imbalance.

## Preparing the train and test sets

### Train-test split

In [355]:
print(df.columns)

Index(['id', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'avg_glucose_level', 'bmi', 'gender_female', 'gender_male',
       'gender_other', 'work_type_govt_job', 'work_type_never_worked',
       'work_type_private', 'work_type_self-employed', 'work_type_children',
       'residence_type_rural', 'residence_type_urban',
       'smoking_status_unknown', 'smoking_status_formerly_smoked',
       'smoking_status_never_smoked', 'smoking_status_smokes', 'stroke'],
      dtype='str')

In [356]:
columns_to_drop = ["ever_married", "gender_female", "gender_male", "gender_other", "work_type_govt_job", "work_type_never_worked",
       "work_type_private", "work_type_self-employed", "work_type_children"]
df = df.drop(columns=columns_to_drop)

In [357]:
X = df.drop(columns=[df.columns[-1]]) 
y = df[df.columns[-1]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Create models

### Random Forests

In [358]:
random_forest_models = {
    "RandomForest_100_5": RandomForestClassifier(
        n_estimators=100,
        max_depth=5
    ),
    "RandomForest_50_5": RandomForestClassifier(
        n_estimators=50,
        max_depth=5
    ),
    "RandomForest_50_10": RandomForestClassifier(
        n_estimators=50,
        max_depth=10
    ),
    "RandomForest_500_3": RandomForestClassifier(
        n_estimators=500,
        max_depth=3
    ),
    "RandomForest_200_10": RandomForestClassifier(
        n_estimators=200,
        max_depth=10
    ),
    "RandomForest_300_7": RandomForestClassifier(
        n_estimators=300,
        max_depth=7
    ),
}

### Neural Networks

In [359]:
input_shape = X_train.shape[1]

neural_networks_models = {
    "NN_64_32_1": Sequential([
        Dense(64, activation="relu", input_shape=(input_shape,)),
        Dense(32, activation="relu"),
        Dense(1, activation="sigmoid")
    ]),
    "NN_32_32_32_1": Sequential([
        Dense(32, activation="sigmoid", input_shape=(input_shape,)),
        Dense(32, activation="sigmoid"),
        Dense(32, activation="sigmoid"),
        Dense(1, activation="sigmoid")
    ]),
    "NN_64_64_1": Sequential([
        Dense(64, activation="relu", input_shape=(input_shape,)),
        Dense(64, activation="tanh"),
        Dense(1, activation="sigmoid")
    ]),
    "NN_128_64_64_1": Sequential([
        Dense(128, activation="relu", input_shape=(input_shape,)),
        Dense(64, activation="relu"),
        Dense(64, activation="relu"),
        Dense(1, activation="sigmoid")
    ]),
    "NN_64_1": Sequential([
        Dense(64, activation="relu", input_shape=(input_shape,)),
        Dense(1, activation="sigmoid")
    ]),
    "NN_64_32_64_1": Sequential([
        Dense(64, activation="relu", input_shape=(input_shape,)),
        Dense(32, activation="tanh"),
        Dense(64, activation="tanh"),
        Dense(1, activation="sigmoid")
    ]),
}

c:\Users\Dell\anaconda\envs\tensorflow\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

## Train models

### Using SMOTE to deal with class imbalance

#### Cross-validation pipeline

In [360]:
def validate_models_smote(models, X, y):
    results = {}

    for name, model in models.items():
        pipeline = Pipeline([
            ("scaler", StandardScaler()),
            ("smote", SMOTE(sampling_strategy="minority")),
            ("model", model)
        ])

        scores = cross_validate(pipeline, X, y, cv=5, scoring=["precision", "recall", "f1"])
        results[name] = {
            "precision": scores["test_precision"].mean(),
            "recall": scores["test_recall"].mean(),
            "f1": scores["test_f1"].mean(),
        }

    return results

In [361]:
results = validate_models_smote(random_forest_models, X_train, y_train)
for name, result in results.items():
    print(f"{name}: {result}\n")

RandomForest_100_5: {'precision': np.float64(0.11538325995754026), 'recall': np.float64(0.759317211948791), 'f1': np.float64(0.200275389176938)}

RandomForest_50_5: {'precision': np.float64(0.11811092355340817), 'recall': np.float64(0.7701280227596017), 'f1': np.float64(0.20470997084023818)}

RandomForest_50_10: {'precision': np.float64(0.11809729236564592), 'recall': np.float64(0.48036984352773826), 'f1': np.float64(0.1893341329390947)}

RandomForest_500_3: {'precision': np.float64(0.11102230909924637), 'recall': np.float64(0.8130867709815078), 'f1': np.float64(0.19531276386306534)}

RandomForest_200_10: {'precision': np.float64(0.115927203357308), 'recall': np.float64(0.4591749644381224), 'f1': np.float64(0.18462075770367764)}

RandomForest_300_7: {'precision': np.float64(0.12058561087639832), 'recall': np.float64(0.6681365576102418), 'f1': np.float64(0.2041737310889158)}

#### Training pipeline

In [362]:
def train_models_smote(models, X, y):

    trained_models = {}

    for name, model in models.items():
        pipeline = Pipeline([
            ("scaler", StandardScaler()),
            ("smote", SMOTE(sampling_strategy="minority")),
            ("model", model)
        ])

        trained_pipeline = pipeline.fit(X, y)
        trained_models[name] = trained_pipeline

    return trained_models

In [363]:
trained_models = train_models_smote(random_forest_models, X_train, y_train)

for name, model in trained_models.items():
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print(f"{name} Accuracy: {accuracy}")
    print(f"{name} Precision: {precision}")
    print(f"{name} Recall: {recall}")
    print(f"{name} F1: {f1}\n")

RandomForest_100_5 Accuracy: 0.7240704500978473
RandomForest_100_5 Precision: 0.15625
RandomForest_100_5 Recall: 0.8064516129032258
RandomForest_100_5 F1: 0.2617801047120419

RandomForest_50_5 Accuracy: 0.7309197651663405
RandomForest_50_5 Precision: 0.15309446254071662
RandomForest_50_5 Recall: 0.7580645161290323
RandomForest_50_5 F1: 0.25474254742547425

RandomForest_50_10 Accuracy: 0.7925636007827789
RandomForest_50_10 Precision: 0.12871287128712872
RandomForest_50_10 Recall: 0.41935483870967744
RandomForest_50_10 F1: 0.19696969696969696

RandomForest_500_3 Accuracy: 0.7064579256360078
RandomForest_500_3 Precision: 0.15
RandomForest_500_3 Recall: 0.8225806451612904
RandomForest_500_3 F1: 0.2537313432835821

RandomForest_200_10 Accuracy: 0.8023483365949119
RandomForest_200_10 Precision: 0.13541666666666666
RandomForest_200_10 Recall: 0.41935483870967744
RandomForest_200_10 F1: 0.2047244094488189

RandomForest_300_7 Accuracy: 0.7524461839530333
RandomForest_300_7 Precision: 0.1552346570397112
RandomForest_300_7 Recall: 0.6935483870967742
RandomForest_300_7 F1: 0.2536873156342183

### Using Ensemble to deal with class imbalance

In [364]:
ensemble_set = pd.concat((X_train.copy(), y_train.copy()), axis="columns")

# Divide the ensemble set by the label
ensemble_class_0 = ensemble_set[ensemble_set[ensemble_set.columns[-1]] == 0]
ensemble_class_1 = ensemble_set[ensemble_set[ensemble_set.columns[-1]] == 1]

# Create train and test sets
X_train_class_0 = ensemble_class_0.drop(ensemble_class_0.columns[-1], axis="columns")
y_train_class_0 = ensemble_class_0[ensemble_class_0.columns[-1]]

X_train_class_1 = ensemble_class_1.drop(ensemble_class_1.columns[-1], axis="columns")
y_train_class_1 = ensemble_class_1[ensemble_class_1.columns[-1]]

# Estimate the number of sub models required and the numer of class 0 records per each sub model
sub_models_count = int(len(X_train_class_0) / len(X_train_class_1))
records_per_set = len(X_train_class_0) // sub_models_count

ensemble_models = {}
for name, model in random_forest_models.items():
    ensemble_model = []
    for i in range(sub_models_count):
        X_chunk = X_train_class_0.sample(n=records_per_set, replace=True)
        y_chunk = y_train_class_0.loc[X_chunk.index]
        current_X_train = pd.concat((X_chunk, X_train_class_1), axis="rows")
        current_y_train = pd.concat((y_chunk, y_train_class_1), axis="rows")

        trained_model = clone(model)
        trained_model.fit(current_X_train, current_y_train)
        ensemble_model.append(trained_model)

    ensemble_models[name] = ensemble_model

In [365]:
for name, model in ensemble_models.items():
    votes = np.zeros(len(X_test))

    for sub_model in model:
        prob = sub_model.predict_proba(X_test)[:, 1]
        votes += prob

    avg_prob = votes / len(model)

    thresholds = np.linspace(0.01, 0.5, 50)
    for threshold in thresholds:
        print(f"CURRENT THRESHOLD: {threshold}")
        y_pred = (avg_prob > threshold).astype(int)

        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        print(f"{name} Accuracy: {accuracy}")
        print(f"{name} Precision: {precision}")
        print(f"{name} Recall: {recall}")
        print(f"{name} F1: {f1}\n")

CURRENT THRESHOLD: 0.01
RandomForest_100_5 Accuracy: 0.060665362035225046
RandomForest_100_5 Precision: 0.060665362035225046
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.11439114391143912

CURRENT THRESHOLD: 0.02
RandomForest_100_5 Accuracy: 0.060665362035225046
RandomForest_100_5 Precision: 0.060665362035225046
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.11439114391143912

CURRENT THRESHOLD: 0.03
RandomForest_100_5 Accuracy: 0.060665362035225046
RandomForest_100_5 Precision: 0.060665362035225046
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.11439114391143912

CURRENT THRESHOLD: 0.04
RandomForest_100_5 Accuracy: 0.060665362035225046
RandomForest_100_5 Precision: 0.060665362035225046
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.11439114391143912

CURRENT THRESHOLD: 0.05
RandomForest_100_5 Accuracy: 0.07045009784735812
RandomForest_100_5 Precision: 0.06126482213438735
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.1154562383612663

CURRENT THRESHOLD: 0.060000000000000005
RandomForest_100_5 Accuracy: 0.11252446183953033
RandomForest_100_5 Precision: 0.06398348813209494
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.12027158098933075

CURRENT THRESHOLD: 0.06999999999999999
RandomForest_100_5 Accuracy: 0.13111545988258316
RandomForest_100_5 Precision: 0.06526315789473684
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.1225296442687747

CURRENT THRESHOLD: 0.08
RandomForest_100_5 Accuracy: 0.14579256360078277
RandomForest_100_5 Precision: 0.06631016042780749
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.12437311935807423

CURRENT THRESHOLD: 0.09
RandomForest_100_5 Accuracy: 0.15557729941291584
RandomForest_100_5 Precision: 0.06702702702702702
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.12563323201621074

CURRENT THRESHOLD: 0.09999999999999999
RandomForest_100_5 Accuracy: 0.16927592954990214
RandomForest_100_5 Precision: 0.06805708013172337
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.12744090441932168

CURRENT THRESHOLD: 0.11
RandomForest_100_5 Accuracy: 0.18297455968688844
RandomForest_100_5 Precision: 0.06911928651059086
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.12930135557872785

CURRENT THRESHOLD: 0.12
RandomForest_100_5 Accuracy: 0.2025440313111546
RandomForest_100_5 Precision: 0.07069555302166476
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.13205537806176784

CURRENT THRESHOLD: 0.13
RandomForest_100_5 Accuracy: 0.2181996086105675
RandomForest_100_5 Precision: 0.07200929152148665
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.13434452871072589

CURRENT THRESHOLD: 0.14
RandomForest_100_5 Accuracy: 0.2455968688845401
RandomForest_100_5 Precision: 0.0744297719087635
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.13854748603351955

CURRENT THRESHOLD: 0.15000000000000002
RandomForest_100_5 Accuracy: 0.27690802348336596
RandomForest_100_5 Precision: 0.07740324594257178
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.1436848203939745

CURRENT THRESHOLD: 0.16
RandomForest_100_5 Accuracy: 0.3101761252446184
RandomForest_100_5 Precision: 0.08083441981747067
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.14957780458383596

CURRENT THRESHOLD: 0.17
RandomForest_100_5 Accuracy: 0.33463796477495106
RandomForest_100_5 Precision: 0.08355795148247978
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.15422885572139303

CURRENT THRESHOLD: 0.18000000000000002
RandomForest_100_5 Accuracy: 0.3659491193737769
RandomForest_100_5 Precision: 0.08732394366197183
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.16062176165803108

CURRENT THRESHOLD: 0.19
RandomForest_100_5 Accuracy: 0.3943248532289628
RandomForest_100_5 Precision: 0.09104258443465492
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.16689098250336473

CURRENT THRESHOLD: 0.2
RandomForest_100_5 Accuracy: 0.4158512720156556
RandomForest_100_5 Precision: 0.09408194233687406
RandomForest_100_5 Recall: 1.0
RandomForest_100_5 F1: 0.17198335644937587

CURRENT THRESHOLD: 0.21000000000000002
RandomForest_100_5 Accuracy: 0.4471624266144814
RandomForest_100_5 Precision: 0.09630818619582665
RandomForest_100_5 Recall: 0.967741935483871
RandomForest_100_5 F1: 0.17518248175182483

CURRENT THRESHOLD: 0.22
RandomForest_100_5 Accuracy: 0.461839530332681
RandomForest_100_5 Precision: 0.09868421052631579
RandomForest_100_5 Recall: 0.967741935483871
RandomForest_100_5 F1: 0.1791044776119403

CURRENT THRESHOLD: 0.23
RandomForest_100_5 Accuracy: 0.47162426614481406
RandomForest_100_5 Precision: 0.10033444816053512
RandomForest_100_5 Recall: 0.967741935483871
RandomForest_100_5 F1: 0.18181818181818182

CURRENT THRESHOLD: 0.24000000000000002
RandomForest_100_5 Accuracy: 0.4882583170254403
RandomForest_100_5 Precision: 0.10327022375215146
RandomForest_100_5 Recall: 0.967741935483871
RandomForest_100_5 F1: 0.18662519440124417

CURRENT THRESHOLD: 0.25
RandomForest_100_5 Accuracy: 0.49412915851272016
RandomForest_100_5 Precision: 0.10296684118673648
RandomForest_100_5 Recall: 0.9516129032258065
RandomForest_100_5 F1: 0.1858267716535433

CURRENT THRESHOLD: 0.26
RandomForest_100_5 Accuracy: 0.5048923679060665
RandomForest_100_5 Precision: 0.10498220640569395
RandomForest_100_5 Recall: 0.9516129032258065
RandomForest_100_5 F1: 0.1891025641025641

CURRENT THRESHOLD: 0.27
RandomForest_100_5 Accuracy: 0.5117416829745597
RandomForest_100_5 Precision: 0.1063063063063063
RandomForest_100_5 Recall: 0.9516129032258065
RandomForest_100_5 F1: 0.1912479740680713

CURRENT THRESHOLD: 0.28
RandomForest_100_5 Accuracy: 0.5205479452054794
RandomForest_100_5 Precision: 0.10805860805860806
RandomForest_100_5 Recall: 0.9516129032258065
RandomForest_100_5 F1: 0.19407894736842105

CURRENT THRESHOLD: 0.29000000000000004
RandomForest_100_5 Accuracy: 0.5303326810176126
RandomForest_100_5 Precision: 0.10861423220973783
RandomForest_100_5 Recall: 0.9354838709677419
RandomForest_100_5 F1: 0.19463087248322147

CURRENT THRESHOLD: 0.3
RandomForest_100_5 Accuracy: 0.5401174168297456
RandomForest_100_5 Precision: 0.11068702290076336
RandomForest_100_5 Recall: 0.9354838709677419
RandomForest_100_5 F1: 0.19795221843003413

CURRENT THRESHOLD: 0.31
RandomForest_100_5 Accuracy: 0.5499021526418787
RandomForest_100_5 Precision: 0.11284046692607004
RandomForest_100_5 Recall: 0.9354838709677419
RandomForest_100_5 F1: 0.2013888888888889

CURRENT THRESHOLD: 0.32
RandomForest_100_5 Accuracy: 0.5587084148727984
RandomForest_100_5 Precision: 0.11485148514851486
RandomForest_100_5 Recall: 0.9354838709677419
RandomForest_100_5 F1: 0.20458553791887124

CURRENT THRESHOLD: 0.33
RandomForest_100_5 Accuracy: 0.5665362035225049
RandomForest_100_5 Precision: 0.11670020120724346
RandomForest_100_5 Recall: 0.9354838709677419
RandomForest_100_5 F1: 0.2075134168157424

CURRENT THRESHOLD: 0.34
RandomForest_100_5 Accuracy: 0.5753424657534246
RandomForest_100_5 Precision: 0.11885245901639344
RandomForest_100_5 Recall: 0.9354838709677419
RandomForest_100_5 F1: 0.2109090909090909

CURRENT THRESHOLD: 0.35000000000000003
RandomForest_100_5 Accuracy: 0.5831702544031311
RandomForest_100_5 Precision: 0.12083333333333333
RandomForest_100_5 Recall: 0.9354838709677419
RandomForest_100_5 F1: 0.2140221402214022

CURRENT THRESHOLD: 0.36000000000000004
RandomForest_100_5 Accuracy: 0.5909980430528375
RandomForest_100_5 Precision: 0.1228813559322034
RandomForest_100_5 Recall: 0.9354838709677419
RandomForest_100_5 F1: 0.21722846441947566

CURRENT THRESHOLD: 0.37
RandomForest_100_5 Accuracy: 0.598825831702544
RandomForest_100_5 Precision: 0.125
RandomForest_100_5 Recall: 0.9354838709677419
RandomForest_100_5 F1: 0.22053231939163498

CURRENT THRESHOLD: 0.38
RandomForest_100_5 Accuracy: 0.6066536203522505
RandomForest_100_5 Precision: 0.12719298245614036
RandomForest_100_5 Recall: 0.9354838709677419
RandomForest_100_5 F1: 0.22393822393822393

CURRENT THRESHOLD: 0.39
RandomForest_100_5 Accuracy: 0.6174168297455969
RandomForest_100_5 Precision: 0.12866817155756208
RandomForest_100_5 Recall: 0.9193548387096774
RandomForest_100_5 F1: 0.22574257425742575

CURRENT THRESHOLD: 0.4
RandomForest_100_5 Accuracy: 0.6223091976516634
RandomForest_100_5 Precision: 0.13013698630136986
RandomForest_100_5 Recall: 0.9193548387096774
RandomForest_100_5 F1: 0.228

CURRENT THRESHOLD: 0.41000000000000003
RandomForest_100_5 Accuracy: 0.6311154598825832
RandomForest_100_5 Precision: 0.13286713286713286
RandomForest_100_5 Recall: 0.9193548387096774
RandomForest_100_5 F1: 0.23217922606924643

CURRENT THRESHOLD: 0.42000000000000004
RandomForest_100_5 Accuracy: 0.6389432485322897
RandomForest_100_5 Precision: 0.13539192399049882
RandomForest_100_5 Recall: 0.9193548387096774
RandomForest_100_5 F1: 0.2360248447204969

CURRENT THRESHOLD: 0.43
RandomForest_100_5 Accuracy: 0.6477495107632094
RandomForest_100_5 Precision: 0.1383495145631068
RandomForest_100_5 Recall: 0.9193548387096774
RandomForest_100_5 F1: 0.24050632911392406

CURRENT THRESHOLD: 0.44
RandomForest_100_5 Accuracy: 0.6575342465753424
RandomForest_100_5 Precision: 0.1417910447761194
RandomForest_100_5 Recall: 0.9193548387096774
RandomForest_100_5 F1: 0.24568965517241378

CURRENT THRESHOLD: 0.45
RandomForest_100_5 Accuracy: 0.662426614481409
RandomForest_100_5 Precision: 0.14357682619647355
RandomForest_100_5 Recall: 0.9193548387096774
RandomForest_100_5 F1: 0.24836601307189543

CURRENT THRESHOLD: 0.46
RandomForest_100_5 Accuracy: 0.6663405088062623
RandomForest_100_5 Precision: 0.1432225063938619
RandomForest_100_5 Recall: 0.9032258064516129
RandomForest_100_5 F1: 0.24724061810154527

CURRENT THRESHOLD: 0.47000000000000003
RandomForest_100_5 Accuracy: 0.6741682974559687
RandomForest_100_5 Precision: 0.1462140992167102
RandomForest_100_5 Recall: 0.9032258064516129
RandomForest_100_5 F1: 0.251685393258427

CURRENT THRESHOLD: 0.48000000000000004
RandomForest_100_5 Accuracy: 0.6829745596868885
RandomForest_100_5 Precision: 0.1497326203208556
RandomForest_100_5 Recall: 0.9032258064516129
RandomForest_100_5 F1: 0.25688073394495414

CURRENT THRESHOLD: 0.49
RandomForest_100_5 Accuracy: 0.6966731898238747
RandomForest_100_5 Precision: 0.15363128491620112
RandomForest_100_5 Recall: 0.8870967741935484
RandomForest_100_5 F1: 0.2619047619047619

CURRENT THRESHOLD: 0.5
RandomForest_100_5 Accuracy: 0.7123287671232876
RandomForest_100_5 Precision: 0.1608187134502924
RandomForest_100_5 Recall: 0.8870967741935484
RandomForest_100_5 F1: 0.2722772277227723

CURRENT THRESHOLD: 0.01
RandomForest_50_5 Accuracy: 0.060665362035225046
RandomForest_50_5 Precision: 0.060665362035225046
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.11439114391143912

CURRENT THRESHOLD: 0.02
RandomForest_50_5 Accuracy: 0.060665362035225046
RandomForest_50_5 Precision: 0.060665362035225046
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.11439114391143912

CURRENT THRESHOLD: 0.03
RandomForest_50_5 Accuracy: 0.060665362035225046
RandomForest_50_5 Precision: 0.060665362035225046
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.11439114391143912

CURRENT THRESHOLD: 0.04
RandomForest_50_5 Accuracy: 0.060665362035225046
RandomForest_50_5 Precision: 0.060665362035225046
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.11439114391143912

CURRENT THRESHOLD: 0.05
RandomForest_50_5 Accuracy: 0.06947162426614481
RandomForest_50_5 Precision: 0.06120434353405726
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.11534883720930232

CURRENT THRESHOLD: 0.060000000000000005
RandomForest_50_5 Accuracy: 0.10567514677103718
RandomForest_50_5 Precision: 0.06352459016393443
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.11946050096339114

CURRENT THRESHOLD: 0.06999999999999999
RandomForest_50_5 Accuracy: 0.12426614481409001
RandomForest_50_5 Precision: 0.06478578892371996
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.12168792934249265

CURRENT THRESHOLD: 0.08
RandomForest_50_5 Accuracy: 0.1379647749510763
RandomForest_50_5 Precision: 0.06574761399787911
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.12338308457711443

CURRENT THRESHOLD: 0.09
RandomForest_50_5 Accuracy: 0.15362035225048923
RandomForest_50_5 Precision: 0.0668824163969795
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.12537917087967643

CURRENT THRESHOLD: 0.09999999999999999
RandomForest_50_5 Accuracy: 0.17221135029354206
RandomForest_50_5 Precision: 0.06828193832599119
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.12783505154639174

CURRENT THRESHOLD: 0.11
RandomForest_50_5 Accuracy: 0.18199608610567514
RandomForest_50_5 Precision: 0.06904231625835189
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.12916666666666668

CURRENT THRESHOLD: 0.12
RandomForest_50_5 Accuracy: 0.19765166340508805
RandomForest_50_5 Precision: 0.07029478458049887
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.13135593220338984

CURRENT THRESHOLD: 0.13
RandomForest_50_5 Accuracy: 0.21135029354207435
RandomForest_50_5 Precision: 0.07142857142857142
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.13333333333333333

CURRENT THRESHOLD: 0.14
RandomForest_50_5 Accuracy: 0.23776908023483365
RandomForest_50_5 Precision: 0.07372175980975029
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.13732004429678848

CURRENT THRESHOLD: 0.15000000000000002
RandomForest_50_5 Accuracy: 0.26810176125244617
RandomForest_50_5 Precision: 0.07654320987654321
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.14220183486238533

CURRENT THRESHOLD: 0.16
RandomForest_50_5 Accuracy: 0.2945205479452055
RandomForest_50_5 Precision: 0.07918263090676884
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.1467455621301775

CURRENT THRESHOLD: 0.17
RandomForest_50_5 Accuracy: 0.3238747553816047
RandomForest_50_5 Precision: 0.08233731739707835
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.1521472392638037

CURRENT THRESHOLD: 0.18000000000000002
RandomForest_50_5 Accuracy: 0.3532289628180039
RandomForest_50_5 Precision: 0.08575380359612725
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.15796178343949044

CURRENT THRESHOLD: 0.19
RandomForest_50_5 Accuracy: 0.3835616438356164
RandomForest_50_5 Precision: 0.08959537572254335
RandomForest_50_5 Recall: 1.0
RandomForest_50_5 F1: 0.16445623342175067

CURRENT THRESHOLD: 0.2
RandomForest_50_5 Accuracy: 0.40313111545988256
RandomForest_50_5 Precision: 0.09104477611940298
RandomForest_50_5 Recall: 0.9838709677419355
RandomForest_50_5 F1: 0.16666666666666666

CURRENT THRESHOLD: 0.21000000000000002
RandomForest_50_5 Accuracy: 0.43052837573385516
RandomForest_50_5 Precision: 0.09375
RandomForest_50_5 Recall: 0.967741935483871
RandomForest_50_5 F1: 0.17094017094017094

CURRENT THRESHOLD: 0.22
RandomForest_50_5 Accuracy: 0.45596868884540115
RandomForest_50_5 Precision: 0.09771986970684039
RandomForest_50_5 Recall: 0.967741935483871
RandomForest_50_5 F1: 0.17751479289940827

CURRENT THRESHOLD: 0.23
RandomForest_50_5 Accuracy: 0.4706457925636008
RandomForest_50_5 Precision: 0.1001669449081803
RandomForest_50_5 Recall: 0.967741935483871
RandomForest_50_5 F1: 0.1815431164901664

CURRENT THRESHOLD: 0.24000000000000002
RandomForest_50_5 Accuracy: 0.4765166340508806
RandomForest_50_5 Precision: 0.09983079526226735
RandomForest_50_5 Recall: 0.9516129032258065
RandomForest_50_5 F1: 0.1807044410413476

CURRENT THRESHOLD: 0.25
RandomForest_50_5 Accuracy: 0.4882583170254403
RandomForest_50_5 Precision: 0.10189982728842832
RandomForest_50_5 Recall: 0.9516129032258065
RandomForest_50_5 F1: 0.18408736349453977

CURRENT THRESHOLD: 0.26
RandomForest_50_5 Accuracy: 0.5039138943248532
RandomForest_50_5 Precision: 0.10479573712255773
RandomForest_50_5 Recall: 0.9516129032258065
RandomForest_50_5 F1: 0.1888

CURRENT THRESHOLD: 0.27
RandomForest_50_5 Accuracy: 0.5078277886497065
RandomForest_50_5 Precision: 0.10554561717352415
RandomForest_50_5 Recall: 0.9516129032258065
RandomForest_50_5 F1: 0.19001610305958133

CURRENT THRESHOLD: 0.28
RandomForest_50_5 Accuracy: 0.5185909980430529
RandomForest_50_5 Precision: 0.10766423357664233
RandomForest_50_5 Recall: 0.9516129032258065
RandomForest_50_5 F1: 0.19344262295081968

CURRENT THRESHOLD: 0.29000000000000004
RandomForest_50_5 Accuracy: 0.5273972602739726
RandomForest_50_5 Precision: 0.10800744878957169
RandomForest_50_5 Recall: 0.9354838709677419
RandomForest_50_5 F1: 0.19365609348914858

CURRENT THRESHOLD: 0.3
RandomForest_50_5 Accuracy: 0.5342465753424658
RandomForest_50_5 Precision: 0.10943396226415095
RandomForest_50_5 Recall: 0.9354838709677419
RandomForest_50_5 F1: 0.19594594594594594

CURRENT THRESHOLD: 0.31
RandomForest_50_5 Accuracy: 0.541095890410959
RandomForest_50_5 Precision: 0.11089866156787763
RandomForest_50_5 Recall: 0.9354838709677419
RandomForest_50_5 F1: 0.19829059829059828

CURRENT THRESHOLD: 0.32
RandomForest_50_5 Accuracy: 0.5499021526418787
RandomForest_50_5 Precision: 0.11284046692607004
RandomForest_50_5 Recall: 0.9354838709677419
RandomForest_50_5 F1: 0.2013888888888889

CURRENT THRESHOLD: 0.33
RandomForest_50_5 Accuracy: 0.5636007827788649
RandomForest_50_5 Precision: 0.116
RandomForest_50_5 Recall: 0.9354838709677419
RandomForest_50_5 F1: 0.20640569395017794

CURRENT THRESHOLD: 0.34
RandomForest_50_5 Accuracy: 0.5704500978473581
RandomForest_50_5 Precision: 0.11764705882352941
RandomForest_50_5 Recall: 0.9354838709677419
RandomForest_50_5 F1: 0.209009009009009

CURRENT THRESHOLD: 0.35000000000000003
RandomForest_50_5 Accuracy: 0.5792563600782779
RandomForest_50_5 Precision: 0.11983471074380166
RandomForest_50_5 Recall: 0.9354838709677419
RandomForest_50_5 F1: 0.21245421245421245

CURRENT THRESHOLD: 0.36000000000000004
RandomForest_50_5 Accuracy: 0.5870841487279843
RandomForest_50_5 Precision: 0.12184873949579832
RandomForest_50_5 Recall: 0.9354838709677419
RandomForest_50_5 F1: 0.21561338289962825

CURRENT THRESHOLD: 0.37
RandomForest_50_5 Accuracy: 0.5978473581213307
RandomForest_50_5 Precision: 0.12473118279569892
RandomForest_50_5 Recall: 0.9354838709677419
RandomForest_50_5 F1: 0.22011385199240988

CURRENT THRESHOLD: 0.38
RandomForest_50_5 Accuracy: 0.6066536203522505
RandomForest_50_5 Precision: 0.12719298245614036
RandomForest_50_5 Recall: 0.9354838709677419
RandomForest_50_5 F1: 0.22393822393822393

CURRENT THRESHOLD: 0.39
RandomForest_50_5 Accuracy: 0.6125244618395304
RandomForest_50_5 Precision: 0.12723214285714285
RandomForest_50_5 Recall: 0.9193548387096774
RandomForest_50_5 F1: 0.2235294117647059

CURRENT THRESHOLD: 0.4
RandomForest_50_5 Accuracy: 0.6193737769080235
RandomForest_50_5 Precision: 0.1292517006802721
RandomForest_50_5 Recall: 0.9193548387096774
RandomForest_50_5 F1: 0.22664015904572565

CURRENT THRESHOLD: 0.41000000000000003
RandomForest_50_5 Accuracy: 0.6281800391389433
RandomForest_50_5 Precision: 0.13194444444444445
RandomForest_50_5 Recall: 0.9193548387096774
RandomForest_50_5 F1: 0.23076923076923078

CURRENT THRESHOLD: 0.42000000000000004
RandomForest_50_5 Accuracy: 0.6428571428571429
RandomForest_50_5 Precision: 0.1366906474820144
RandomForest_50_5 Recall: 0.9193548387096774
RandomForest_50_5 F1: 0.23799582463465555

CURRENT THRESHOLD: 0.43
RandomForest_50_5 Accuracy: 0.6477495107632094
RandomForest_50_5 Precision: 0.1383495145631068
RandomForest_50_5 Recall: 0.9193548387096774
RandomForest_50_5 F1: 0.24050632911392406

CURRENT THRESHOLD: 0.44
RandomForest_50_5 Accuracy: 0.6575342465753424
RandomForest_50_5 Precision: 0.14
RandomForest_50_5 Recall: 0.9032258064516129
RandomForest_50_5 F1: 0.24242424242424243

CURRENT THRESHOLD: 0.45
RandomForest_50_5 Accuracy: 0.6663405088062623
RandomForest_50_5 Precision: 0.1432225063938619
RandomForest_50_5 Recall: 0.9032258064516129
RandomForest_50_5 F1: 0.24724061810154527

CURRENT THRESHOLD: 0.46
RandomForest_50_5 Accuracy: 0.678082191780822
RandomForest_50_5 Precision: 0.14775725593667546
RandomForest_50_5 Recall: 0.9032258064516129
RandomForest_50_5 F1: 0.25396825396825395

CURRENT THRESHOLD: 0.47000000000000003
RandomForest_50_5 Accuracy: 0.6888454011741683

### Using class weight to deal with the imbalance

#### Training Neural Networks

In [366]:
def train_neural_networks(models, X, y):
    results = {}

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    for name, model in models.items():
        model_copy = clone_model(model)
        model_copy.set_weights(model.get_weights()) 
        
        model_copy.compile(optimizer=Adam(learning_rate=0.001), loss="binary_crossentropy", metrics=["precision", "recall"])
        model_copy.fit(X_scaled, y, epochs=50, batch_size=32, verbose=0, class_weight={0: 1, 1: 19}, validation_split=0.2)

        results[name] = model_copy

    return results, scaler

In [367]:
trained_models, scaler = train_neural_networks(neural_networks_models, X_train, y_train)
X_test_scaled = scaler.transform(X_test)

for name, model in trained_models.items():
    y_prob = model.predict(X_test_scaled).flatten()
    thresholds = np.linspace(0.01, 0.9, 50)
    for threshold in thresholds:
        print(f"CURRENT THRESHOLD: {threshold}")
        y_pred = (y_prob > threshold).astype(int) 

        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        print(f"{name} Accuracy: {accuracy}")
        print(f"{name} Precision: {precision}")
        print(f"{name} Recall: {recall}")
        print(f"{name} F1: {f1}\n")

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
CURRENT THRESHOLD: 0.01
NN_64_32_1 Accuracy: 0.38943248532289626
NN_64_32_1 Precision: 0.0891812865497076
NN_64_32_1 Recall: 0.9838709677419355
NN_64_32_1 F1: 0.16353887399463807

CURRENT THRESHOLD: 0.028163265306122447
NN_64_32_1 Accuracy: 0.4628180039138943
NN_64_32_1 Precision: 0.09484193011647254
NN_64_32_1 Recall: 0.9193548387096774
NN_64_32_1 F1: 0.17194570135746606

CURRENT THRESHOLD: 0.0463265306122449
NN_64_32_1 Accuracy: 0.5117416829745597
NN_64_32_1 Precision: 0.10200364298724955
NN_64_32_1 Recall: 0.9032258064516129
NN_64_32_1 F1: 0.18330605564648117

CURRENT THRESHOLD: 0.06448979591836734
NN_64_32_1 Accuracy: 0.5371819960861057
NN_64_32_1 Precision: 0.10556621880998081
NN_64_32_1 Recall: 0.8870967741935484
NN_64_32_1 F1: 0.18867924528301888

CURRENT THRESHOLD: 0.08265306122448979
NN_64_32_1 Accuracy: 0.5606653620352251
NN_64_32_1 Precision: 0.1075050709939148
NN_64_32_1 Recall: 0.8548387096774194
NN_64_32_1 F1: 0.19099099099099098

CURRENT THRESHOLD: 0.10081632653061223
NN_64_32_1 Accuracy: 0.5812133072407045
NN_64_32_1 Precision: 0.10897435897435898
NN_64_32_1 Recall: 0.8225806451612904
NN_64_32_1 F1: 0.19245283018867926

CURRENT THRESHOLD: 0.11897959183673469
NN_64_32_1 Accuracy: 0.5968688845401174
NN_64_32_1 Precision: 0.1111111111111111
NN_64_32_1 Recall: 0.8064516129032258
NN_64_32_1 F1: 0.1953125

CURRENT THRESHOLD: 0.13714285714285715
NN_64_32_1 Accuracy: 0.6223091976516634
NN_64_32_1 Precision: 0.1179245283018868
NN_64_32_1 Recall: 0.8064516129032258
NN_64_32_1 F1: 0.205761316872428

CURRENT THRESHOLD: 0.1553061224489796
NN_64_32_1 Accuracy: 0.6389432485322897
NN_64_32_1 Precision: 0.12285012285012285
NN_64_32_1 Recall: 0.8064516129032258
NN_64_32_1 F1: 0.21321961620469082

CURRENT THRESHOLD: 0.17346938775510204
NN_64_32_1 Accuracy: 0.649706457925636
NN_64_32_1 Precision: 0.12626262626262627
NN_64_32_1 Recall: 0.8064516129032258
NN_64_32_1 F1: 0.2183406113537118

CURRENT THRESHOLD: 0.19163265306122448
NN_64_32_1 Accuracy: 0.6663405088062623
NN_64_32_1 Precision: 0.1260053619302949
NN_64_32_1 Recall: 0.7580645161290323
NN_64_32_1 F1: 0.2160919540229885

CURRENT THRESHOLD: 0.20979591836734693
NN_64_32_1 Accuracy: 0.6839530332681018
NN_64_32_1 Precision: 0.1323943661971831
NN_64_32_1 Recall: 0.7580645161290323
NN_64_32_1 F1: 0.22541966426858512

CURRENT THRESHOLD: 0.2279591836734694
NN_64_32_1 Accuracy: 0.6976516634050881
NN_64_32_1 Precision: 0.1378299120234604
NN_64_32_1 Recall: 0.7580645161290323
NN_64_32_1 F1: 0.23325062034739455

CURRENT THRESHOLD: 0.24612244897959185
NN_64_32_1 Accuracy: 0.7064579256360078
NN_64_32_1 Precision: 0.1393939393939394
NN_64_32_1 Recall: 0.7419354838709677
NN_64_32_1 F1: 0.23469387755102042

CURRENT THRESHOLD: 0.2642857142857143
NN_64_32_1 Accuracy: 0.7172211350293543
NN_64_32_1 Precision: 0.14420062695924765
NN_64_32_1 Recall: 0.7419354838709677
NN_64_32_1 F1: 0.24146981627296588

CURRENT THRESHOLD: 0.28244897959183674
NN_64_32_1 Accuracy: 0.7270058708414873
NN_64_32_1 Precision: 0.1488673139158576
NN_64_32_1 Recall: 0.7419354838709677
NN_64_32_1 F1: 0.24797843665768193

CURRENT THRESHOLD: 0.3006122448979592
NN_64_32_1 Accuracy: 0.738747553816047
NN_64_32_1 Precision: 0.15488215488215487
NN_64_32_1 Recall: 0.7419354838709677
NN_64_32_1 F1: 0.2562674094707521

CURRENT THRESHOLD: 0.3187755102040816
NN_64_32_1 Accuracy: 0.7407045009784736
NN_64_32_1 Precision: 0.14878892733564014
NN_64_32_1 Recall: 0.6935483870967742
NN_64_32_1 F1: 0.245014245014245

CURRENT THRESHOLD: 0.33693877551020407
NN_64_32_1 Accuracy: 0.7485322896281801
NN_64_32_1 Precision: 0.15302491103202848
NN_64_32_1 Recall: 0.6935483870967742
NN_64_32_1 F1: 0.25072886297376096

CURRENT THRESHOLD: 0.3551020408163265
NN_64_32_1 Accuracy: 0.7563600782778865
NN_64_32_1 Precision: 0.15498154981549817
NN_64_32_1 Recall: 0.6774193548387096
NN_64_32_1 F1: 0.25225225225225223

CURRENT THRESHOLD: 0.37326530612244896
NN_64_32_1 Accuracy: 0.764187866927593
NN_64_32_1 Precision: 0.1517509727626459
NN_64_32_1 Recall: 0.6290322580645161
NN_64_32_1 F1: 0.2445141065830721

CURRENT THRESHOLD: 0.3914285714285714
NN_64_32_1 Accuracy: 0.7710371819960861
NN_64_32_1 Precision: 0.156
NN_64_32_1 Recall: 0.6290322580645161
NN_64_32_1 F1: 0.25

CURRENT THRESHOLD: 0.40959183673469385
NN_64_32_1 Accuracy: 0.7788649706457925
NN_64_32_1 Precision: 0.16115702479338842
NN_64_32_1 Recall: 0.6290322580645161
NN_64_32_1 F1: 0.2565789473684211

CURRENT THRESHOLD: 0.4277551020408163
NN_64_32_1 Accuracy: 0.7915851272015656
NN_64_32_1 Precision: 0.1703056768558952
NN_64_32_1 Recall: 0.6290322580645161
NN_64_32_1 F1: 0.26804123711340205

CURRENT THRESHOLD: 0.4459183673469388
NN_64_32_1 Accuracy: 0.7984344422700587
NN_64_32_1 Precision: 0.17272727272727273
NN_64_32_1 Recall: 0.6129032258064516
NN_64_32_1 F1: 0.2695035460992908

CURRENT THRESHOLD: 0.46408163265306124
NN_64_32_1 Accuracy: 0.8013698630136986
NN_64_32_1 Precision: 0.16267942583732056
NN_64_32_1 Recall: 0.5483870967741935
NN_64_32_1 F1: 0.25092250922509224

CURRENT THRESHOLD: 0.4822448979591837
NN_64_32_1 Accuracy: 0.8101761252446184
NN_64_32_1 Precision: 0.17
NN_64_32_1 Recall: 0.5483870967741935
NN_64_32_1 F1: 0.2595419847328244

CURRENT THRESHOLD: 0.5004081632653061
NN_64_32_1 Accuracy: 0.8180039138943248
NN_64_32_1 Precision: 0.17708333333333334
NN_64_32_1 Recall: 0.5483870967741935
NN_64_32_1 F1: 0.2677165354330709

CURRENT THRESHOLD: 0.5185714285714286
NN_64_32_1 Accuracy: 0.8268101761252447
NN_64_32_1 Precision: 0.18579234972677597
NN_64_32_1 Recall: 0.5483870967741935
NN_64_32_1 F1: 0.27755102040816326

CURRENT THRESHOLD: 0.536734693877551
NN_64_32_1 Accuracy: 0.8336594911937377
NN_64_32_1 Precision: 0.1896551724137931
NN_64_32_1 Recall: 0.532258064516129
NN_64_32_1 F1: 0.2796610169491525

CURRENT THRESHOLD: 0.5548979591836735
NN_64_32_1 Accuracy: 0.8365949119373777
NN_64_32_1 Precision: 0.1893491124260355
NN_64_32_1 Recall: 0.5161290322580645
NN_64_32_1 F1: 0.27705627705627706

CURRENT THRESHOLD: 0.5730612244897959
NN_64_32_1 Accuracy: 0.8414872798434442
NN_64_32_1 Precision: 0.1951219512195122
NN_64_32_1 Recall: 0.5161290322580645
NN_64_32_1 F1: 0.2831858407079646

CURRENT THRESHOLD: 0.5912244897959184
NN_64_32_1 Accuracy: 0.8424657534246576
NN_64_32_1 Precision: 0.18867924528301888
NN_64_32_1 Recall: 0.4838709677419355
NN_64_32_1 F1: 0.27149321266968324

CURRENT THRESHOLD: 0.6093877551020408
NN_64_32_1 Accuracy: 0.8493150684931506
NN_64_32_1 Precision: 0.19333333333333333
NN_64_32_1 Recall: 0.46774193548387094
NN_64_32_1 F1: 0.27358490566037735

CURRENT THRESHOLD: 0.6275510204081632
NN_64_32_1 Accuracy: 0.8522504892367906
NN_64_32_1 Precision: 0.19310344827586207
NN_64_32_1 Recall: 0.45161290322580644
NN_64_32_1 F1: 0.27053140096618356

CURRENT THRESHOLD: 0.6457142857142857
NN_64_32_1 Accuracy: 0.860078277886497
NN_64_32_1 Precision: 0.20437956204379562
NN_64_32_1 Recall: 0.45161290322580644
NN_64_32_1 F1: 0.2814070351758794

CURRENT THRESHOLD: 0.6638775510204081
NN_64_32_1 Accuracy: 0.8679060665362035
NN_64_32_1 Precision: 0.208
NN_64_32_1 Recall: 0.41935483870967744
NN_64_32_1 F1: 0.27807486631016043

CURRENT THRESHOLD: 0.6820408163265306
NN_64_32_1 Accuracy: 0.8737769080234834
NN_64_32_1 Precision: 0.2184873949579832
NN_64_32_1 Recall: 0.41935483870967744
NN_64_32_1 F1: 0.287292817679558

CURRENT THRESHOLD: 0.700204081632653
NN_64_32_1 Accuracy: 0.8767123287671232
NN_64_32_1 Precision: 0.21929824561403508
NN_64_32_1 Recall: 0.4032258064516129
NN_64_32_1 F1: 0.2840909090909091

CURRENT THRESHOLD: 0.7183673469387755
NN_64_32_1 Accuracy: 0.8776908023483366
NN_64_32_1 Precision: 0.21100917431192662
NN_64_32_1 Recall: 0.3709677419354839
NN_64_32_1 F1: 0.26900584795321636

CURRENT THRESHOLD: 0.7365306122448979
NN_64_32_1 Accuracy: 0.8845401174168297
NN_64_32_1 Precision: 0.22549019607843138
NN_64_32_1 Recall: 0.3709677419354839
NN_64_32_1 F1: 0.2804878048780488

CURRENT THRESHOLD: 0.7546938775510204
NN_64_32_1 Accuracy: 0.8943248532289628
NN_64_32_1 Precision: 0.23255813953488372
NN_64_32_1 Recall: 0.3225806451612903
NN_64_32_1 F1: 0.2702702702702703

CURRENT THRESHOLD: 0.7728571428571428
NN_64_32_1 Accuracy: 0.898238747553816
NN_64_32_1 Precision: 0.24390243902439024
NN_64_32_1 Recall: 0.3225806451612903
NN_64_32_1 F1: 0.2777777777777778

CURRENT THRESHOLD: 0.7910204081632652
NN_64_32_1 Accuracy: 0.9070450097847358
NN_64_32_1 Precision: 0.273972602739726
NN_64_32_1 Recall: 0.3225806451612903
NN_64_32_1 F1: 0.2962962962962963

CURRENT THRESHOLD: 0.8091836734693877
NN_64_32_1 Accuracy: 0.9129158512720157
NN_64_32_1 Precision: 0.29850746268656714
NN_64_32_1 Recall: 0.3225806451612903
NN_64_32_1 F1: 0.31007751937984496

CURRENT THRESHOLD: 0.8273469387755101
NN_64_32_1 Accuracy: 0.9148727984344422
NN_64_32_1 Precision: 0.2807017543859649
NN_64_32_1 Recall: 0.25806451612903225
NN_64_32_1 F1: 0.2689075630252101

CURRENT THRESHOLD: 0.8455102040816326
NN_64_32_1 Accuracy: 0.9187866927592955
NN_64_32_1 Precision: 0.3018867924528302
NN_64_32_1 Recall: 0.25806451612903225
NN_64_32_1 F1: 0.2782608695652174

CURRENT THRESHOLD: 0.863673469387755
NN_64_32_1 Accuracy: 0.9246575342465754
NN_64_32_1 Precision: 0.3170731707317073
NN_64_32_1 Recall: 0.20967741935483872
NN_64_32_1 F1: 0.2524271844660194

CURRENT THRESHOLD: 0.8818367346938776
NN_64_32_1 Accuracy: 0.9275929549902152
NN_64_32_1 Precision: 0.3333333333333333
NN_64_32_1 Recall: 0.1935483870967742
NN_64_32_1 F1: 0.24489795918367346

CURRENT THRESHOLD: 0.9
NN_64_32_1 Accuracy: 0.9315068493150684
NN_64_32_1 Precision: 0.35714285714285715
NN_64_32_1 Recall: 0.16129032258064516
NN_64_32_1 F1: 0.2222222222222222

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
CURRENT THRESHOLD: 0.01
NN_32_32_32_1 Accuracy: 0.060665362035225046
NN_32_32_32_1 Precision: 0.060665362035225046
NN_32_32_32_1 Recall: 1.0
NN_32_32_32_1 F1: 0.11439114391143912

CURRENT THRESHOLD: 0.028163265306122447
NN_32_32_32_1 Accuracy: 0.060665362035225046
NN_32_32_32_1 Precision: 0.060665362035225046
NN_32_32_32_1 Recall: 1.0
NN_32_32_32_1 F1: 0.11439114391143912

CURRENT THRESHOLD: 0.0463265306122449
NN_32_32_32_1 Accuracy: 0.1888454011741683
NN_32_32_32_1 Precision: 0.06958473625140292
NN_32_32_32_1 Recall: 1.0
NN_32_32_32_1 F1: 0.13011542497376705

CURRENT THRESHOLD: 0.06448979591836734
NN_32_32_32_1 Accuracy: 0.3101761252446184
NN_32_32_32_1 Precision: 0.08083441981747067
NN_32_32_32_1 Recall: 1.0
NN_32_32_32_1 F1: 0.14957780458383596

CURRENT THRESHOLD: 0.08265306122448979
NN_32_32_32_1 Accuracy: 0.3816046966731898
NN_32_32_32_1 Precision: 0.0893371757925072
NN_32_32_32_1 Recall: 1.0
NN_32_32_32_1 F1: 0.164021164021164

CURRENT THRESHOLD: 0.10081632653061223
NN_32_32_32_1 Accuracy: 0.4187866927592955
NN_32_32_32_1 Precision: 0.09451219512195122
NN_32_32_32_1 Recall: 1.0
NN_32_32_32_1 F1: 0.17270194986072424

CURRENT THRESHOLD: 0.11897959183673469
NN_32_32_32_1 Accuracy: 0.45499021526418787
NN_32_32_32_1 Precision: 0.09886547811993517
NN_32_32_32_1 Recall: 0.9838709677419355
NN_32_32_32_1 F1: 0.1796759941089838

CURRENT THRESHOLD: 0.13714285714285715
NN_32_32_32_1 Accuracy: 0.4765166340508806
NN_32_32_32_1 Precision: 0.10252100840336134
NN_32_32_32_1 Recall: 0.9838709677419355
NN_32_32_32_1 F1: 0.1856925418569254

CURRENT THRESHOLD: 0.1553061224489796
NN_32_32_32_1 Accuracy: 0.49706457925636005
NN_32_32_32_1 Precision: 0.1048951048951049
NN_32_32_32_1 Recall: 0.967741935483871
NN_32_32_32_1 F1: 0.1892744479495268

CURRENT THRESHOLD: 0.17346938775510204
NN_32_32_32_1 Accuracy: 0.5117416829745597
NN_32_32_32_1 Precision: 0.1063063063063063
NN_32_32_32_1 Recall: 0.9516129032258065
NN_32_32_32_1 F1: 0.1912479740680713

CURRENT THRESHOLD: 0.19163265306122448
NN_32_32_32_1 Accuracy: 0.525440313111546
NN_32_32_32_1 Precision: 0.10905730129390019
NN_32_32_32_1 Recall: 0.9516129032258065
NN_32_32_32_1 F1: 0.1956882255389718

CURRENT THRESHOLD: 0.20979591836734693
NN_32_32_32_1 Accuracy: 0.5371819960861057
NN_32_32_32_1 Precision: 0.11005692599620494
NN_32_32_32_1 Recall: 0.9354838709677419
NN_32_32_32_1 F1: 0.1969439728353141

CURRENT THRESHOLD: 0.2279591836734694
NN_32_32_32_1 Accuracy: 0.5538160469667319
NN_32_32_32_1 Precision: 0.11372549019607843
NN_32_32_32_1 Recall: 0.9354838709677419
NN_32_32_32_1 F1: 0.20279720279720279

CURRENT THRESHOLD: 0.24612244897959185
NN_32_32_32_1 Accuracy: 0.5724070450097848
NN_32_32_32_1 Precision: 0.11812627291242363
NN_32_32_32_1 Recall: 0.9354838709677419
NN_32_32_32_1 F1: 0.20976491862567812

CURRENT THRESHOLD: 0.2642857142857143
NN_32_32_32_1 Accuracy: 0.5880626223091977
NN_32_32_32_1 Precision: 0.12210526315789473
NN_32_32_32_1 Recall: 0.9354838709677419
NN_32_32_32_1 F1: 0.21601489757914338

CURRENT THRESHOLD: 0.28244897959183674
NN_32_32_32_1 Accuracy: 0.5958904109589042
NN_32_32_32_1 Precision: 0.12258064516129032
NN_32_32_32_1 Recall: 0.9193548387096774
NN_32_32_32_1 F1: 0.21631878557874762

CURRENT THRESHOLD: 0.3006122448979592
NN_32_32_32_1 Accuracy: 0.6154598825831703
NN_32_32_32_1 Precision: 0.12808988764044943
NN_32_32_32_1 Recall: 0.9193548387096774
NN_32_32_32_1 F1: 0.22485207100591717

CURRENT THRESHOLD: 0.3187755102040816
NN_32_32_32_1 Accuracy: 0.6291585127201565
NN_32_32_32_1 Precision: 0.13225058004640372
NN_32_32_32_1 Recall: 0.9193548387096774
NN_32_32_32_1 F1: 0.23123732251521298

CURRENT THRESHOLD: 0.33693877551020407
NN_32_32_32_1 Accuracy: 0.6389432485322897
NN_32_32_32_1 Precision: 0.13539192399049882
NN_32_32_32_1 Recall: 0.9193548387096774
NN_32_32_32_1 F1: 0.2360248447204969

CURRENT THRESHOLD: 0.3551020408163265
NN_32_32_32_1 Accuracy: 0.6545988258317026
NN_32_32_32_1 Precision: 0.14074074074074075
NN_32_32_32_1 Recall: 0.9193548387096774
NN_32_32_32_1 F1: 0.24411134903640258

CURRENT THRESHOLD: 0.37326530612244896
NN_32_32_32_1 Accuracy: 0.6653620352250489
NN_32_32_32_1 Precision: 0.14285714285714285
NN_32_32_32_1 Recall: 0.9032258064516129
NN_32_32_32_1 F1: 0.24669603524229075

CURRENT THRESHOLD: 0.3914285714285714
NN_32_32_32_1 Accuracy: 0.675146771037182
NN_32_32_32_1 Precision: 0.14659685863874344
NN_32_32_32_1 Recall: 0.9032258064516129
NN_32_32_32_1 F1: 0.25225225225225223

CURRENT THRESHOLD: 0.40959183673469385
NN_32_32_32_1 Accuracy: 0.6888454011741683
NN_32_32_32_1 Precision: 0.15027322404371585
NN_32_32_32_1 Recall: 0.8870967741935484
NN_32_32_32_1 F1: 0.2570093457943925

CURRENT THRESHOLD: 0.4277551020408163
NN_32_32_32_1 Accuracy: 0.7025440313111546
NN_32_32_32_1 Precision: 0.15229885057471265
NN_32_32_32_1 Recall: 0.8548387096774194
NN_32_32_32_1 F1: 0.25853658536585367

CURRENT THRESHOLD: 0.4459183673469388
NN_32_32_32_1 Accuracy: 0.7084148727984344
NN_32_32_32_1 Precision: 0.1488095238095238
NN_32_32_32_1 Recall: 0.8064516129032258
NN_32_32_32_1 F1: 0.25125628140703515

CURRENT THRESHOLD: 0.46408163265306124
NN_32_32_32_1 Accuracy: 0.7240704500978473
NN_32_32_32_1 Precision: 0.1540880503144654
NN_32_32_32_1 Recall: 0.7903225806451613
NN_32_32_32_1 F1: 0.2578947368421053

CURRENT THRESHOLD: 0.4822448979591837
NN_32_32_32_1 Accuracy: 0.7318982387475538
NN_32_32_32_1 Precision: 0.1513157894736842
NN_32_32_32_1 Recall: 0.7419354838709677
NN_32_32_32_1 F1: 0.25136612021857924

CURRENT THRESHOLD: 0.5004081632653061
NN_32_32_32_1 Accuracy: 0.738747553816047
NN_32_32_32_1 Precision: 0.15488215488215487
NN_32_32_32_1 Recall: 0.7419354838709677
NN_32_32_32_1 F1: 0.2562674094707521

CURRENT THRESHOLD: 0.5185714285714286
NN_32_32_32_1 Accuracy: 0.7514677103718199
NN_32_32_32_1 Precision: 0.1619718309859155
NN_32_32_32_1 Recall: 0.7419354838709677
NN_32_32_32_1 F1: 0.2658959537572254

CURRENT THRESHOLD: 0.536734693877551
NN_32_32_32_1 Accuracy: 0.7632093933463796
NN_32_32_32_1 Precision: 0.16911764705882354
NN_32_32_32_1 Recall: 0.7419354838709677
NN_32_32_32_1 F1: 0.2754491017964072

CURRENT THRESHOLD: 0.5548979591836735
NN_32_32_32_1 Accuracy: 0.7720156555772995
NN_32_32_32_1 Precision: 0.17490494296577946
NN_32_32_32_1 Recall: 0.7419354838709677
NN_32_32_32_1 F1: 0.28307692307692306

CURRENT THRESHOLD: 0.5730612244897959
NN_32_32_32_1 Accuracy: 0.7857142857142857
NN_32_32_32_1 Precision: 0.17959183673469387
NN_32_32_32_1 Recall: 0.7096774193548387
NN_32_32_32_1 F1: 0.28664495114006516

CURRENT THRESHOLD: 0.5912244897959184
NN_32_32_32_1 Accuracy: 0.7925636007827789
NN_32_32_32_1 Precision: 0.18220338983050846
NN_32_32_32_1 Recall: 0.6935483870967742
NN_32_32_32_1 F1: 0.28859060402684567

CURRENT THRESHOLD: 0.6093877551020408
NN_32_32_32_1 Accuracy: 0.8052837573385518
NN_32_32_32_1 Precision: 0.18433179723502305
NN_32_32_32_1 Recall: 0.6451612903225806
NN_32_32_32_1 F1: 0.2867383512544803

CURRENT THRESHOLD: 0.6275510204081632
NN_32_32_32_1 Accuracy: 0.8091976516634051
NN_32_32_32_1 Precision: 0.18779342723004694
NN_32_32_32_1 Recall: 0.6451612903225806
NN_32_32_32_1 F1: 0.2909090909090909

CURRENT THRESHOLD: 0.6457142857142857
NN_32_32_32_1 Accuracy: 0.8189823874755382
NN_32_32_32_1 Precision: 0.19402985074626866
NN_32_32_32_1 Recall: 0.6290322580645161
NN_32_32_32_1 F1: 0.2965779467680608

CURRENT THRESHOLD: 0.6638775510204081
NN_32_32_32_1 Accuracy: 0.8268101761252447
NN_32_32_32_1 Precision: 0.1925133689839572
NN_32_32_32_1 Recall: 0.5806451612903226
NN_32_32_32_1 F1: 0.2891566265060241

CURRENT THRESHOLD: 0.6820408163265306
NN_32_32_32_1 Accuracy: 0.8405088062622309
NN_32_32_32_1 Precision: 0.2046783625730994
NN_32_32_32_1 Recall: 0.5645161290322581
NN_32_32_32_1 F1: 0.30042918454935624

CURRENT THRESHOLD: 0.700204081632653
NN_32_32_32_1 Accuracy: 0.8493150684931506
NN_32_32_32_1 Precision: 0.2125
NN_32_32_32_1 Recall: 0.5483870967741935
NN_32_32_32_1 F1: 0.3063063063063063

CURRENT THRESHOLD: 0.7183673469387755
NN_32_32_32_1 Accuracy: 0.8561643835616438
NN_32_32_32_1 Precision: 0.2222222222222222
NN_32_32_32_1 Recall: 0.5483870967741935
NN_32_32_32_1 F1: 0.31627906976744186

CURRENT THRESHOLD: 0.7365306122448979
NN_32_32_32_1 Accuracy: 0.8708414872798435
NN_32_32_32_1 Precision: 0.2463768115942029
NN_32_32_32_1 Recall: 0.5483870967741935
NN_32_32_32_1 F1: 0.34

CURRENT THRESHOLD: 0.7546938775510204
NN_32_32_32_1 Accuracy: 0.8845401174168297
NN_32_32_32_1 Precision: 0.27049180327868855
NN_32_32_32_1 Recall: 0.532258064516129
NN_32_32_32_1 F1: 0.358695652173913

CURRENT THRESHOLD: 0.7728571428571428
NN_32_32_32_1 Accuracy: 0.8992172211350293
NN_32_32_32_1 Precision: 0.28865979381443296
NN_32_32_32_1 Recall: 0.45161290322580644
NN_32_32_32_1 F1: 0.3522012578616352

CURRENT THRESHOLD: 0.7910204081632652
NN_32_32_32_1 Accuracy: 0.9178082191780822
NN_32_32_32_1 Precision: 0.34285714285714286
NN_32_32_32_1 Recall: 0.3870967741935484
NN_32_32_32_1 F1: 0.36363636363636365

CURRENT THRESHOLD: 0.8091836734693877
NN_32_32_32_1 Accuracy: 0.9275929549902152
NN_32_32_32_1 Precision: 0.35714285714285715
NN_32_32_32_1 Recall: 0.24193548387096775
NN_32_32_32_1 F1: 0.28846153846153844

CURRENT THRESHOLD: 0.8273469387755101
NN_32_32_32_1 Accuracy: 0.9334637964774951
NN_32_32_32_1 Precision: 0.39285714285714285
NN_32_32_32_1 Recall: 0.1774193548387097
NN_32_32_32_1 F1: 0.24444444444444444

CURRENT THRESHOLD: 0.8455102040816326
NN_32_32_32_1 Accuracy: 0.9354207436399217
NN_32_32_32_1 Precision: 0.3
NN_32_32_32_1 Recall: 0.04838709677419355
NN_32_32_32_1 F1: 0.08333333333333333

CURRENT THRESHOLD: 0.863673469387755
NN_32_32_32_1 Accuracy: 0.9393346379647749
NN_32_32_32_1 Precision: 0.0
NN_32_32_32_1 Recall: 0.0
NN_32_32_32_1 F1: 0.0

CURRENT THRESHOLD: 0.8818367346938776
NN_32_32_32_1 Accuracy: 0.9393346379647749
NN_32_32_32_1 Precision: 0.0
NN_32_32_32_1 Recall: 0.0
NN_32_32_32_1 F1: 0.0

CURRENT THRESHOLD: 0.9
NN_32_32_32_1 Accuracy: 0.9393346379647749
NN_32_32_32_1 Precision: 0.0
NN_32_32_32_1 Recall: 0.0
NN_32_32_32_1 F1: 0.0

 1/32 ━━━━━━━━━━━━━━━━━━━━ 2s 87ms/step

c:\Users\Dell\anaconda\envs\tensorflow\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Dell\anaconda\envs\tensorflow\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Dell\anaconda\envs\tensorflow\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
CURRENT THRESHOLD: 0.01
NN_64_64_1 Accuracy: 0.3385518590998043
NN_64_64_1 Precision: 0.08401084010840108
NN_64_64_1 Recall: 1.0
NN_64_64_1 F1: 0.155

CURRENT THRESHOLD: 0.028163265306122447
NN_64_64_1 Accuracy: 0.3933463796477495
NN_64_64_1 Precision: 0.08849557522123894
NN_64_64_1 Recall: 0.967741935483871
NN_64_64_1 F1: 0.16216216216216217

CURRENT THRESHOLD: 0.0463265306122449
NN_64_64_1 Accuracy: 0.4246575342465753
NN_64_64_1 Precision: 0.09034267912772585
NN_64_64_1 Recall: 0.9354838709677419
NN_64_64_1 F1: 0.16477272727272727

CURRENT THRESHOLD: 0.06448979591836734
NN_64_64_1 Accuracy: 0.45792563600782776
NN_64_64_1 Precision: 0.09271523178807947
NN_64_64_1 Recall: 0.9032258064516129
NN_64_64_1 F1: 0.16816816816816818

CURRENT THRESHOLD: 0.08265306122448979
NN_64_64_1 Accuracy: 0.49510763209393344
NN_64_64_1 Precision: 0.0989399293286219
NN_64_64_1 Recall: 0.9032258064516129
NN_64_64_1 F1: 0.17834394904458598

CURRENT THRESHOLD: 0.10081632653061223
NN_64_64_1 Accuracy: 0.5185909980430529
NN_64_64_1 Precision: 0.1033210332103321
NN_64_64_1 Recall: 0.9032258064516129
NN_64_64_1 F1: 0.18543046357615894

CURRENT THRESHOLD: 0.11897959183673469
NN_64_64_1 Accuracy: 0.5273972602739726
NN_64_64_1 Precision: 0.10357815442561205
NN_64_64_1 Recall: 0.8870967741935484
NN_64_64_1 F1: 0.18549747048903878

CURRENT THRESHOLD: 0.13714285714285715
NN_64_64_1 Accuracy: 0.5450097847358122
NN_64_64_1 Precision: 0.10721247563352826
NN_64_64_1 Recall: 0.8870967741935484
NN_64_64_1 F1: 0.19130434782608696

CURRENT THRESHOLD: 0.1553061224489796
NN_64_64_1 Accuracy: 0.5675146771037182
NN_64_64_1 Precision: 0.11224489795918367
NN_64_64_1 Recall: 0.8870967741935484
NN_64_64_1 F1: 0.19927536231884058

CURRENT THRESHOLD: 0.17346938775510204
NN_64_64_1 Accuracy: 0.5909980430528375
NN_64_64_1 Precision: 0.11471861471861472
NN_64_64_1 Recall: 0.8548387096774194
NN_64_64_1 F1: 0.20229007633587787

CURRENT THRESHOLD: 0.19163265306122448
NN_64_64_1 Accuracy: 0.6037181996086106
NN_64_64_1 Precision: 0.1146067415730337
NN_64_64_1 Recall: 0.8225806451612904
NN_64_64_1 F1: 0.20118343195266272

CURRENT THRESHOLD: 0.20979591836734693
NN_64_64_1 Accuracy: 0.6154598825831703
NN_64_64_1 Precision: 0.11778290993071594
NN_64_64_1 Recall: 0.8225806451612904
NN_64_64_1 F1: 0.20606060606060606

CURRENT THRESHOLD: 0.2279591836734694
NN_64_64_1 Accuracy: 0.6360078277886497
NN_64_64_1 Precision: 0.12378640776699029
NN_64_64_1 Recall: 0.8225806451612904
NN_64_64_1 F1: 0.21518987341772153

CURRENT THRESHOLD: 0.24612244897959185
NN_64_64_1 Accuracy: 0.6487279843444227
NN_64_64_1 Precision: 0.12781954887218044
NN_64_64_1 Recall: 0.8225806451612904
NN_64_64_1 F1: 0.22125813449023862

CURRENT THRESHOLD: 0.2642857142857143
NN_64_64_1 Accuracy: 0.6594911937377691
NN_64_64_1 Precision: 0.12760416666666666
NN_64_64_1 Recall: 0.7903225806451613
NN_64_64_1 F1: 0.21973094170403587

CURRENT THRESHOLD: 0.28244897959183674
NN_64_64_1 Accuracy: 0.6663405088062623
NN_64_64_1 Precision: 0.129973474801061
NN_64_64_1 Recall: 0.7903225806451613
NN_64_64_1 F1: 0.22323462414578588

CURRENT THRESHOLD: 0.3006122448979592
NN_64_64_1 Accuracy: 0.6741682974559687
NN_64_64_1 Precision: 0.1307901907356948
NN_64_64_1 Recall: 0.7741935483870968
NN_64_64_1 F1: 0.22377622377622378

CURRENT THRESHOLD: 0.3187755102040816
NN_64_64_1 Accuracy: 0.687866927592955
NN_64_64_1 Precision: 0.1359773371104816
NN_64_64_1 Recall: 0.7741935483870968
NN_64_64_1 F1: 0.23132530120481928

CURRENT THRESHOLD: 0.33693877551020407
NN_64_64_1 Accuracy: 0.6966731898238747
NN_64_64_1 Precision: 0.13742690058479531
NN_64_64_1 Recall: 0.7580645161290323
NN_64_64_1 F1: 0.23267326732673269

CURRENT THRESHOLD: 0.3551020408163265
NN_64_64_1 Accuracy: 0.7074363992172211
NN_64_64_1 Precision: 0.1419939577039275
NN_64_64_1 Recall: 0.7580645161290323
NN_64_64_1 F1: 0.23918575063613232

CURRENT THRESHOLD: 0.37326530612244896
NN_64_64_1 Accuracy: 0.7181996086105675
NN_64_64_1 Precision: 0.14240506329113925
NN_64_64_1 Recall: 0.7258064516129032
NN_64_64_1 F1: 0.23809523809523808

CURRENT THRESHOLD: 0.3914285714285714
NN_64_64_1 Accuracy: 0.7289628180039139
NN_64_64_1 Precision: 0.14754098360655737
NN_64_64_1 Recall: 0.7258064516129032
NN_64_64_1 F1: 0.2452316076294278

CURRENT THRESHOLD: 0.40959183673469385
NN_64_64_1 Accuracy: 0.7338551859099804
NN_64_64_1 Precision: 0.1476510067114094
NN_64_64_1 Recall: 0.7096774193548387
NN_64_64_1 F1: 0.24444444444444444

CURRENT THRESHOLD: 0.4277551020408163
NN_64_64_1 Accuracy: 0.7367906066536204
NN_64_64_1 Precision: 0.14186851211072665
NN_64_64_1 Recall: 0.6612903225806451
NN_64_64_1 F1: 0.2336182336182336

CURRENT THRESHOLD: 0.4459183673469388
NN_64_64_1 Accuracy: 0.7465753424657534
NN_64_64_1 Precision: 0.14695340501792115
NN_64_64_1 Recall: 0.6612903225806451
NN_64_64_1 F1: 0.2404692082111437

CURRENT THRESHOLD: 0.46408163265306124
NN_64_64_1 Accuracy: 0.7602739726027398
NN_64_64_1 Precision: 0.15471698113207547
NN_64_64_1 Recall: 0.6612903225806451
NN_64_64_1 F1: 0.25076452599388377

CURRENT THRESHOLD: 0.4822448979591837
NN_64_64_1 Accuracy: 0.7681017612524462
NN_64_64_1 Precision: 0.15953307392996108
NN_64_64_1 Recall: 0.6612903225806451
NN_64_64_1 F1: 0.25705329153605017

CURRENT THRESHOLD: 0.5004081632653061
NN_64_64_1 Accuracy: 0.7720156555772995
NN_64_64_1 Precision: 0.1593625498007968
NN_64_64_1 Recall: 0.6451612903225806
NN_64_64_1 F1: 0.25559105431309903

CURRENT THRESHOLD: 0.5185714285714286
NN_64_64_1 Accuracy: 0.7798434442270059
NN_64_64_1 Precision: 0.16182572614107885
NN_64_64_1 Recall: 0.6290322580645161
NN_64_64_1 F1: 0.25742574257425743

CURRENT THRESHOLD: 0.536734693877551
NN_64_64_1 Accuracy: 0.7876712328767124
NN_64_64_1 Precision: 0.16738197424892703
NN_64_64_1 Recall: 0.6290322580645161
NN_64_64_1 F1: 0.26440677966101694

CURRENT THRESHOLD: 0.5548979591836735
NN_64_64_1 Accuracy: 0.8013698630136986
NN_64_64_1 Precision: 0.1780821917808219
NN_64_64_1 Recall: 0.6290322580645161
NN_64_64_1 F1: 0.2775800711743772

CURRENT THRESHOLD: 0.5730612244897959
NN_64_64_1 Accuracy: 0.812133072407045
NN_64_64_1 Precision: 0.18446601941747573
NN_64_64_1 Recall: 0.6129032258064516
NN_64_64_1 F1: 0.2835820895522388

CURRENT THRESHOLD: 0.5912244897959184
NN_64_64_1 Accuracy: 0.8238747553816047
NN_64_64_1 Precision: 0.1958762886597938
NN_64_64_1 Recall: 0.6129032258064516
NN_64_64_1 F1: 0.296875

CURRENT THRESHOLD: 0.6093877551020408
NN_64_64_1 Accuracy: 0.8258317025440313
NN_64_64_1 Precision: 0.1881720430107527
NN_64_64_1 Recall: 0.5645161290322581
NN_64_64_1 F1: 0.28225806451612906

CURRENT THRESHOLD: 0.6275510204081632
NN_64_64_1 Accuracy: 0.8326810176125244
NN_64_64_1 Precision: 0.192090395480226
NN_64_64_1 Recall: 0.5483870967741935
NN_64_64_1 F1: 0.28451882845188287

CURRENT THRESHOLD: 0.6457142857142857
NN_64_64_1 Accuracy: 0.8385518590998043
NN_64_64_1 Precision: 0.19161676646706588
NN_64_64_1 Recall: 0.5161290322580645
NN_64_64_1 F1: 0.2794759825327511

CURRENT THRESHOLD: 0.6638775510204081
NN_64_64_1 Accuracy: 0.8483365949119374
NN_64_64_1 Precision: 0.19607843137254902
NN_64_64_1 Recall: 0.4838709677419355
NN_64_64_1 F1: 0.27906976744186046

CURRENT THRESHOLD: 0.6820408163265306
NN_64_64_1 Accuracy: 0.8571428571428571
NN_64_64_1 Precision: 0.20422535211267606
NN_64_64_1 Recall: 0.46774193548387094
NN_64_64_1 F1: 0.28431372549019607

CURRENT THRESHOLD: 0.700204081632653
NN_64_64_1 Accuracy: 0.8620352250489237
NN_64_64_1 Precision: 0.1984732824427481
NN_64_64_1 Recall: 0.41935483870967744
NN_64_64_1 F1: 0.2694300518134715

CURRENT THRESHOLD: 0.7183673469387755
NN_64_64_1 Accuracy: 0.8669275929549902
NN_64_64_1 Precision: 0.19672131147540983
NN_64_64_1 Recall: 0.3870967741935484
NN_64_64_1 F1: 0.2608695652173913

CURRENT THRESHOLD: 0.7365306122448979
NN_64_64_1 Accuracy: 0.8767123287671232
NN_64_64_1 Precision: 0.21428571428571427
NN_64_64_1 Recall: 0.3870967741935484
NN_64_64_1 F1: 0.27586206896551724

CURRENT THRESHOLD: 0.7546938775510204
NN_64_64_1 Accuracy: 0.8806262230919765
NN_64_64_1 Precision: 0.2222222222222222
NN_64_64_1 Recall: 0.3870967741935484
NN_64_64_1 F1: 0.2823529411764706

CURRENT THRESHOLD: 0.7728571428571428
NN_64_64_1 Accuracy: 0.8835616438356164
NN_64_64_1 Precision: 0.21212121212121213
NN_64_64_1 Recall: 0.3387096774193548
NN_64_64_1 F1: 0.2608695652173913

CURRENT THRESHOLD: 0.7910204081632652
NN_64_64_1 Accuracy: 0.8962818003913894
NN_64_64_1 Precision: 0.2441860465116279
NN_64_64_1 Recall: 0.3387096774193548
NN_64_64_1 F1: 0.28378378378378377

CURRENT THRESHOLD: 0.8091836734693877
NN_64_64_1 Accuracy: 0.8972602739726028
NN_64_64_1 Precision: 0.22077922077922077
NN_64_64_1 Recall: 0.27419354838709675
NN_64_64_1 F1: 0.2446043165467626

CURRENT THRESHOLD: 0.8273469387755101
NN_64_64_1 Accuracy: 0.9031311154598826
NN_64_64_1 Precision: 0.23943661971830985
NN_64_64_1 Recall: 0.27419354838709675
NN_64_64_1 F1: 0.2556390977443609

CURRENT THRESHOLD: 0.8455102040816326
NN_64_64_1 Accuracy: 0.9031311154598826
NN_64_64_1 Precision: 0.19672131147540983
NN_64_64_1 Recall: 0.1935483870967742
NN_64_64_1 F1: 0.1951219512195122

CURRENT THRESHOLD: 0.863673469387755
NN_64_64_1 Accuracy: 0.9041095890410958
NN_64_64_1 Precision: 0.16666666666666666
NN_64_64_1 Recall: 0.14516129032258066
NN_64_64_1 F1: 0.15517241379310345

CURRENT THRESHOLD: 0.8818367346938776
NN_64_64_1 Accuracy: 0.9119373776908023
NN_64_64_1 Precision: 0.16666666666666666
NN_64_64_1 Recall: 0.11290322580645161
NN_64_64_1 F1: 0.1346153846153846

CURRENT THRESHOLD: 0.9
NN_64_64_1 Accuracy: 0.913894324853229
NN_64_64_1 Precision: 0.09375
NN_64_64_1 Recall: 0.04838709677419355
NN_64_64_1 F1: 0.06382978723404255

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
CURRENT THRESHOLD: 0.01
NN_128_64_64_1 Accuracy: 0.713307240704501
NN_128_64_64_1 Precision: 0.12131147540983607
NN_128_64_64_1 Recall: 0.5967741935483871
NN_128_64_64_1 F1: 0.2016348773841962

CURRENT THRESHOLD: 0.028163265306122447
NN_128_64_64_1 Accuracy: 0.7495107632093934
NN_128_64_64_1 Precision: 0.11507936507936507
NN_128_64_64_1 Recall: 0.46774193548387094
NN_128_64_64_1 F1: 0.18471337579617833

CURRENT THRESHOLD: 0.0463265306122449
NN_128_64_64_1 Accuracy: 0.773972602739726
NN_128_64_64_1 Precision: 0.12444444444444444
NN_128_64_64_1 Recall: 0.45161290322580644
NN_128_64_64_1 F1: 0.1951219512195122

CURRENT THRESHOLD: 0.06448979591836734
NN_128_64_64_1 Accuracy: 0.7827788649706457
NN_128_64_64_1 Precision: 0.1261682242990654
NN_128_64_64_1 Recall: 0.43548387096774194
NN_128_64_64_1 F1: 0.1956521739130435

CURRENT THRESHOLD: 0.08265306122448979
NN_128_64_64_1 Accuracy: 0.7945205479452054
NN_128_64_64_1 Precision: 0.13366336633663367
NN_128_64_64_1 Recall: 0.43548387096774194
NN_128_64_64_1 F1: 0.20454545454545456

CURRENT THRESHOLD: 0.10081632653061223
NN_128_64_64_1 Accuracy: 0.8023483365949119
NN_128_64_64_1 Precision: 0.13157894736842105
NN_128_64_64_1 Recall: 0.4032258064516129
NN_128_64_64_1 F1: 0.1984126984126984

CURRENT THRESHOLD: 0.11897959183673469
NN_128_64_64_1 Accuracy: 0.8111545988258317
NN_128_64_64_1 Precision: 0.1340782122905028
NN_128_64_64_1 Recall: 0.3870967741935484
NN_128_64_64_1 F1: 0.1991701244813278

CURRENT THRESHOLD: 0.13714285714285715
NN_128_64_64_1 Accuracy: 0.8170254403131115
NN_128_64_64_1 Precision: 0.13450292397660818
NN_128_64_64_1 Recall: 0.3709677419354839
NN_128_64_64_1 F1: 0.19742489270386265

CURRENT THRESHOLD: 0.1553061224489796
NN_128_64_64_1 Accuracy: 0.8199608610567515
NN_128_64_64_1 Precision: 0.13253012048192772
NN_128_64_64_1 Recall: 0.3548387096774194
NN_128_64_64_1 F1: 0.19298245614035087

CURRENT THRESHOLD: 0.17346938775510204
NN_128_64_64_1 Accuracy: 0.8287671232876712
NN_128_64_64_1 Precision: 0.14012738853503184
NN_128_64_64_1 Recall: 0.3548387096774194
NN_128_64_64_1 F1: 0.2009132420091324

CURRENT THRESHOLD: 0.19163265306122448
NN_128_64_64_1 Accuracy: 0.8326810176125244
NN_128_64_64_1 Precision: 0.1437908496732026
NN_128_64_64_1 Recall: 0.3548387096774194
NN_128_64_64_1 F1: 0.20465116279069767

CURRENT THRESHOLD: 0.20979591836734693
NN_128_64_64_1 Accuracy: 0.8385518590998043
NN_128_64_64_1 Precision: 0.14965986394557823
NN_128_64_64_1 Recall: 0.3548387096774194
NN_128_64_64_1 F1: 0.21052631578947367

CURRENT THRESHOLD: 0.2279591836734694
NN_128_64_64_1 Accuracy: 0.8434442270058709
NN_128_64_64_1 Precision: 0.15492957746478872
NN_128_64_64_1 Recall: 0.3548387096774194
NN_128_64_64_1 F1: 0.21568627450980393

CURRENT THRESHOLD: 0.24612244897959185
NN_128_64_64_1 Accuracy: 0.8463796477495108
NN_128_64_64_1 Precision: 0.15328467153284672
NN_128_64_64_1 Recall: 0.3387096774193548
NN_128_64_64_1 F1: 0.21105527638190955

CURRENT THRESHOLD: 0.2642857142857143
NN_128_64_64_1 Accuracy: 0.8483365949119374
NN_128_64_64_1 Precision: 0.15037593984962405
NN_128_64_64_1 Recall: 0.3225806451612903
NN_128_64_64_1 F1: 0.20512820512820512

CURRENT THRESHOLD: 0.28244897959183674
NN_128_64_64_1 Accuracy: 0.850293542074364
NN_128_64_64_1 Precision: 0.15267175572519084
NN_128_64_64_1 Recall: 0.3225806451612903
NN_128_64_64_1 F1: 0.20725388601036268

CURRENT THRESHOLD: 0.3006122448979592
NN_128_64_64_1 Accuracy: 0.850293542074364
NN_128_64_64_1 Precision: 0.15267175572519084
NN_128_64_64_1 Recall: 0.3225806451612903
NN_128_64_64_1 F1: 0.20725388601036268

CURRENT THRESHOLD: 0.3187755102040816
NN_128_64_64_1 Accuracy: 0.8512720156555773
NN_128_64_64_1 Precision: 0.14285714285714285
NN_128_64_64_1 Recall: 0.2903225806451613
NN_128_64_64_1 F1: 0.19148936170212766

CURRENT THRESHOLD: 0.33693877551020407
NN_128_64_64_1 Accuracy: 0.8542074363992173
NN_128_64_64_1 Precision: 0.14634146341463414
NN_128_64_64_1 Recall: 0.2903225806451613
NN_128_64_64_1 F1: 0.1945945945945946

CURRENT THRESHOLD: 0.3551020408163265
NN_128_64_64_1 Accuracy: 0.8551859099804305
NN_128_64_64_1 Precision: 0.14754098360655737
NN_128_64_64_1 Recall: 0.2903225806451613
NN_128_64_64_1 F1: 0.1956521739130435

CURRENT THRESHOLD: 0.37326530612244896
NN_128_64_64_1 Accuracy: 0.8590998043052838
NN_128_64_64_1 Precision: 0.15254237288135594
NN_128_64_64_1 Recall: 0.2903225806451613
NN_128_64_64_1 F1: 0.2

CURRENT THRESHOLD: 0.3914285714285714
NN_128_64_64_1 Accuracy: 0.8639921722113503
NN_128_64_64_1 Precision: 0.1592920353982301
NN_128_64_64_1 Recall: 0.2903225806451613
NN_128_64_64_1 F1: 0.2057142857142857

CURRENT THRESHOLD: 0.40959183673469385
NN_128_64_64_1 Accuracy: 0.8669275929549902
NN_128_64_64_1 Precision: 0.16363636363636364
NN_128_64_64_1 Recall: 0.2903225806451613
NN_128_64_64_1 F1: 0.20930232558139536

CURRENT THRESHOLD: 0.4277551020408163
NN_128_64_64_1 Accuracy: 0.8688845401174168
NN_128_64_64_1 Precision: 0.16037735849056603
NN_128_64_64_1 Recall: 0.27419354838709675
NN_128_64_64_1 F1: 0.20238095238095238

CURRENT THRESHOLD: 0.4459183673469388
NN_128_64_64_1 Accuracy: 0.8698630136986302
NN_128_64_64_1 Precision: 0.1553398058252427
NN_128_64_64_1 Recall: 0.25806451612903225
NN_128_64_64_1 F1: 0.19393939393939394

CURRENT THRESHOLD: 0.46408163265306124
NN_128_64_64_1 Accuracy: 0.8708414872798435
NN_128_64_64_1 Precision: 0.1568627450980392
NN_128_64_64_1 Recall: 0.25806451612903225
NN_128_64_64_1 F1: 0.1951219512195122

CURRENT THRESHOLD: 0.4822448979591837
NN_128_64_64_1 Accuracy: 0.8747553816046967
NN_128_64_64_1 Precision: 0.15625
NN_128_64_64_1 Recall: 0.24193548387096775
NN_128_64_64_1 F1: 0.189873417721519

CURRENT THRESHOLD: 0.5004081632653061
NN_128_64_64_1 Accuracy: 0.8776908023483366
NN_128_64_64_1 Precision: 0.15384615384615385
NN_128_64_64_1 Recall: 0.22580645161290322
NN_128_64_64_1 F1: 0.1830065359477124

CURRENT THRESHOLD: 0.5185714285714286
NN_128_64_64_1 Accuracy: 0.8796477495107632
NN_128_64_64_1 Precision: 0.14942528735632185
NN_128_64_64_1 Recall: 0.20967741935483872
NN_128_64_64_1 F1: 0.174496644295302

CURRENT THRESHOLD: 0.536734693877551
NN_128_64_64_1 Accuracy: 0.8796477495107632
NN_128_64_64_1 Precision: 0.1411764705882353
NN_128_64_64_1 Recall: 0.1935483870967742
NN_128_64_64_1 F1: 0.16326530612244897

CURRENT THRESHOLD: 0.5548979591836735
NN_128_64_64_1 Accuracy: 0.8796477495107632
NN_128_64_64_1 Precision: 0.13253012048192772
NN_128_64_64_1 Recall: 0.1774193548387097
NN_128_64_64_1 F1: 0.15172413793103448

CURRENT THRESHOLD: 0.5730612244897959
NN_128_64_64_1 Accuracy: 0.8806262230919765
NN_128_64_64_1 Precision: 0.125
NN_128_64_64_1 Recall: 0.16129032258064516
NN_128_64_64_1 F1: 0.14084507042253522

CURRENT THRESHOLD: 0.5912244897959184
NN_128_64_64_1 Accuracy: 0.8835616438356164
NN_128_64_64_1 Precision: 0.12987012987012986
NN_128_64_64_1 Recall: 0.16129032258064516
NN_128_64_64_1 F1: 0.14388489208633093

CURRENT THRESHOLD: 0.6093877551020408
NN_128_64_64_1 Accuracy: 0.8884540117416829
NN_128_64_64_1 Precision: 0.1388888888888889
NN_128_64_64_1 Recall: 0.16129032258064516
NN_128_64_64_1 F1: 0.14925373134328357

CURRENT THRESHOLD: 0.6275510204081632
NN_128_64_64_1 Accuracy: 0.8904109589041096
NN_128_64_64_1 Precision: 0.1323529411764706
NN_128_64_64_1 Recall: 0.14516129032258066
NN_128_64_64_1 F1: 0.13846153846153847

CURRENT THRESHOLD: 0.6457142857142857
NN_128_64_64_1 Accuracy: 0.8904109589041096
NN_128_64_64_1 Precision: 0.109375
NN_128_64_64_1 Recall: 0.11290322580645161
NN_128_64_64_1 F1: 0.1111111111111111

CURRENT THRESHOLD: 0.6638775510204081
NN_128_64_64_1 Accuracy: 0.8923679060665362
NN_128_64_64_1 Precision: 0.11290322580645161
NN_128_64_64_1 Recall: 0.11290322580645161
NN_128_64_64_1 F1: 0.11290322580645161

CURRENT THRESHOLD: 0.6820408163265306
NN_128_64_64_1 Accuracy: 0.8962818003913894
NN_128_64_64_1 Precision: 0.1206896551724138
NN_128_64_64_1 Recall: 0.11290322580645161
NN_128_64_64_1 F1: 0.11666666666666667

CURRENT THRESHOLD: 0.700204081632653
NN_128_64_64_1 Accuracy: 0.9001956947162426
NN_128_64_64_1 Precision: 0.12962962962962962
NN_128_64_64_1 Recall: 0.11290322580645161
NN_128_64_64_1 F1: 0.1206896551724138

CURRENT THRESHOLD: 0.7183673469387755
NN_128_64_64_1 Accuracy: 0.9021526418786693
NN_128_64_64_1 Precision: 0.1346153846153846
NN_128_64_64_1 Recall: 0.11290322580645161
NN_128_64_64_1 F1: 0.12280701754385964

CURRENT THRESHOLD: 0.7365306122448979
NN_128_64_64_1 Accuracy: 0.9021526418786693
NN_128_64_64_1 Precision: 0.1346153846153846
NN_128_64_64_1 Recall: 0.11290322580645161
NN_128_64_64_1 F1: 0.12280701754385964

CURRENT THRESHOLD: 0.7546938775510204
NN_128_64_64_1 Accuracy: 0.9031311154598826
NN_128_64_64_1 Precision: 0.13725490196078433
NN_128_64_64_1 Recall: 0.11290322580645161
NN_128_64_64_1 F1: 0.12389380530973451

CURRENT THRESHOLD: 0.7728571428571428
NN_128_64_64_1 Accuracy: 0.9060665362035225
NN_128_64_64_1 Precision: 0.13043478260869565
NN_128_64_64_1 Recall: 0.0967741935483871
NN_128_64_64_1 F1: 0.1111111111111111

CURRENT THRESHOLD: 0.7910204081632652
NN_128_64_64_1 Accuracy: 0.9070450097847358
NN_128_64_64_1 Precision: 0.13333333333333333
NN_128_64_64_1 Recall: 0.0967741935483871
NN_128_64_64_1 F1: 0.11214953271028037

CURRENT THRESHOLD: 0.8091836734693877
NN_128_64_64_1 Accuracy: 0.9080234833659491
NN_128_64_64_1 Precision: 0.13636363636363635
NN_128_64_64_1 Recall: 0.0967741935483871
NN_128_64_64_1 F1: 0.11320754716981132

CURRENT THRESHOLD: 0.8273469387755101
NN_128_64_64_1 Accuracy: 0.9119373776908023
NN_128_64_64_1 Precision: 0.15
NN_128_64_64_1 Recall: 0.0967741935483871
NN_128_64_64_1 F1: 0.11764705882352941

CURRENT THRESHOLD: 0.8455102040816326
NN_128_64_64_1 Accuracy: 0.9129158512720157
NN_128_64_64_1 Precision: 0.11428571428571428
NN_128_64_64_1 Recall: 0.06451612903225806
NN_128_64_64_1 F1: 0.08247422680412371

CURRENT THRESHOLD: 0.863673469387755
NN_128_64_64_1 Accuracy: 0.9148727984344422
NN_128_64_64_1 Precision: 0.12121212121212122
NN_128_64_64_1 Recall: 0.06451612903225806
NN_128_64_64_1 F1: 0.08421052631578947

CURRENT THRESHOLD: 0.8818367346938776
NN_128_64_64_1 Accuracy: 0.9178082191780822
NN_128_64_64_1 Precision: 0.13333333333333333
NN_128_64_64_1 Recall: 0.06451612903225806
NN_128_64_64_1 F1: 0.08695652173913043

CURRENT THRESHOLD: 0.9
NN_128_64_64_1 Accuracy: 0.9197651663405088