# Using Machine Learning techniques to predict oral cancer

## Imports

In [39]:
import kagglehub
import os
import pandas as pd

## Load in data, basic data information

In [40]:
path = kagglehub.dataset_download("menegidio/oral-cancer-prediction-dataset")

file_path = os.path.join(path, "oral_cancer_prediction_dataset.csv")
df = pd.read_csv(file_path)

df.head()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

,ID,Country,Age,Gender,Tobacco Use,Alcohol Consumption,HPV Infection,Betel Quid Use,Chronic Sun Exposure,Poor Oral Hygiene,...,Difficulty Swallowing,White or Red Patches in Mouth,Tumor Size (cm),Cancer Stage,Treatment Type,"Survival Rate (5-Year, %)",Cost of Treatment (USD),Economic Burden (Lost Workdays per Year),Early Diagnosis,Oral Cancer (Diagnosis)
0,1,Italy,36,Female,Yes,Yes,Yes,No,No,Yes,...,No,No,0.000000,0,No Treatment,100.000000,0.00,0,No,No
1,2,Japan,64,Male,Yes,Yes,Yes,No,Yes,Yes,...,No,No,1.782186,1,No Treatment,83.340103,77772.50,177,No,Yes
2,3,UK,37,Female,No,Yes,No,No,Yes,Yes,...,No,Yes,3.523895,2,Surgery,63.222871,101164.50,130,Yes,Yes
3,4,Sri Lanka,55,Male,Yes,Yes,No,Yes,No,Yes,...,No,No,0.000000,0,No Treatment,100.000000,0.00,0,Yes,No
4,5,South Africa,68,Male,No,No,No,No,No,Yes,...,No,No,2.834789,3,No Treatment,44.293199,45354.75,52,No,Yes

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84922 entries, 0 to 84921
Data columns (total 25 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   ID                                        84922 non-null  int64
 1   Country                                   84922 non-null  object
 2   Age                                       84922 non-null  int64
 3   Gender                                    84922 non-null  object
 4   Tobacco Use                               84922 non-null  object
 5   Alcohol Consumption                       84922 non-null  object
 6   HPV Infection                             84922 non-null  object
 7   Betel Quid Use                            84922 non-null  object
 8   Chronic Sun Exposure                      84922 non-null  object
 9   Poor Oral Hygiene                         84922 non-null  object
 10  Diet (Fruits & Vegetables Intake)         84922 non-null  object
 11  Family History of Cancer                  84922 non-null  object
 12  Compromised Immune System                 84922 non-null  object
 13  Oral Lesions                              84922 non-null  object
 14  Unexplained Bleeding                      84922 non-null  object
 15  Difficulty Swallowing                     84922 non-null  object
 16  White or Red Patches in Mouth             84922 non-null  object
 17  Tumor Size (cm)                           84922 non-null  float64
 18  Cancer Stage                              84922 non-null  int64
 19  Treatment Type                            84922 non-null  object
 20  Survival Rate (5-Year, %)                 84922 non-null  float64
 21  Cost of Treatment (USD)                   84922 non-null  float64
 22  Economic Burden (Lost Workdays per Year)  84922 non-null  int64
 23  Early Diagnosis                           84922 non-null  object
 24  Oral Cancer (Diagnosis)                   84922 non-null  object
dtypes: float64(3), int64(4), object(18)
memory usage: 16.2+ MB

## Data cleaning

In [43]:
df.columns

Index(['ID', 'Country', 'Age', 'Gender', 'Tobacco Use', 'Alcohol Consumption',
       'HPV Infection', 'Betel Quid Use', 'Chronic Sun Exposure',
       'Poor Oral Hygiene', 'Diet (Fruits & Vegetables Intake)',
       'Family History of Cancer', 'Compromised Immune System', 'Oral Lesions',
       'Unexplained Bleeding', 'Difficulty Swallowing',
       'White or Red Patches in Mouth', 'Tumor Size (cm)', 'Cancer Stage',
       'Treatment Type', 'Survival Rate (5-Year, %)',
       'Cost of Treatment (USD)', 'Economic Burden (Lost Workdays per Year)',
       'Early Diagnosis', 'Oral Cancer (Diagnosis)'],
      dtype='object')

### Dropping columns

In this stage we get rid of features that are synonymous with cancer (eg. Tumor Size, Cancer Stage).

In [44]:
df = df.drop(df.columns[17:-2], axis=1)
df.head()

,ID,Country,Age,Gender,Tobacco Use,Alcohol Consumption,HPV Infection,Betel Quid Use,Chronic Sun Exposure,Poor Oral Hygiene,Diet (Fruits & Vegetables Intake),Family History of Cancer,Compromised Immune System,Oral Lesions,Unexplained Bleeding,Difficulty Swallowing,White or Red Patches in Mouth,Early Diagnosis,Oral Cancer (Diagnosis)
0,1,Italy,36,Female,Yes,Yes,Yes,No,No,Yes,Low,No,No,No,No,No,No,No,No
1,2,Japan,64,Male,Yes,Yes,Yes,No,Yes,Yes,High,No,No,No,Yes,No,No,No,Yes
2,3,UK,37,Female,No,Yes,No,No,Yes,Yes,Moderate,No,No,No,No,No,Yes,Yes,Yes
3,4,Sri Lanka,55,Male,Yes,Yes,No,Yes,No,Yes,Moderate,No,No,Yes,No,No,No,Yes,No
4,5,South Africa,68,Male,No,No,No,No,No,Yes,High,No,No,No,No,No,No,No,Yes