# Using Machine Learning techniques to predict a stroke

## Imports

In [214]:
import kagglehub
import os
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, classification_report
from tensorflow.keras.models import Sequential, clone_model
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

## Load in data, basic data information

In [215]:
path = kagglehub.dataset_download("fedesoriano/stroke-prediction-dataset")

file_path = os.path.join(path, "healthcare-dataset-stroke-data.csv")
df = pd.read_csv(file_path)

df.head()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [216]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   str
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   str
 6   work_type          5110 non-null   str
 7   Residence_type     5110 non-null   str
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   str
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), str(5)
memory usage: 479.2 KB

## Data cleaning

In [217]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='str')

### Checking data for unique values

Before modifying the data to be fit for training we should check how many unique values each feature can have, so that we can determine how to represent it (eg. use 0 and 1 for yes-no columns or one-hot encoding for those with more posiible values).

In [218]:
for column in df.columns:
    print(f"{column} values: {df[column].unique()}")

id values: [ 9046 51676 31112 ... 19723 37544 44679]
gender values: <StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str
age values: [6.70e+01 6.10e+01 8.00e+01 4.90e+01 7.90e+01 8.10e+01 7.40e+01 6.90e+01
 5.90e+01 7.80e+01 5.40e+01 5.00e+01 6.40e+01 7.50e+01 6.00e+01 5.70e+01
 7.10e+01 5.20e+01 8.20e+01 6.50e+01 5.80e+01 4.20e+01 4.80e+01 7.20e+01
 6.30e+01 7.60e+01 3.90e+01 7.70e+01 7.30e+01 5.60e+01 4.50e+01 7.00e+01
 6.60e+01 5.10e+01 4.30e+01 6.80e+01 4.70e+01 5.30e+01 3.80e+01 5.50e+01
 1.32e+00 4.60e+01 3.20e+01 1.40e+01 3.00e+00 8.00e+00 3.70e+01 4.00e+01
 3.50e+01 2.00e+01 4.40e+01 2.50e+01 2.70e+01 2.30e+01 1.70e+01 1.30e+01
 4.00e+00 1.60e+01 2.20e+01 3.00e+01 2.90e+01 1.10e+01 2.10e+01 1.80e+01
 3.30e+01 2.40e+01 3.40e+01 3.60e+01 6.40e-01 4.10e+01 8.80e-01 5.00e+00
 2.60e+01 3.10e+01 7.00e+00 1.20e+01 6.20e+01 2.00e+00 9.00e+00 1.50e+01
 2.80e+01 1.00e+01 1.80e+00 3.20e-01 1.08e+00 1.90e+01 6.00e+00 1.16e+00
 1.00e+00 1.40e+00 1.72e+00 2.40e-01 1.64e+00 1.56e+00 7.20e-01 1.88e+00
 1.24e+00 8.00e-01 4.00e-01 8.00e-02 1.48e+00 5.60e-01 4.80e-01 1.60e-01]
hypertension values: [0 1]
heart_disease values: [1 0]
ever_married values: <StringArray>
['Yes', 'No']
Length: 2, dtype: str
work_type values: <StringArray>
['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked']
Length: 5, dtype: str
Residence_type values: <StringArray>
['Urban', 'Rural']
Length: 2, dtype: str
avg_glucose_level values: [228.69 202.21 105.92 ...  82.99 166.29  85.28]
bmi values: [36.6  nan 32.5 34.4 24.  29.  27.4 22.8 24.2 29.7 36.8 27.3 28.2 30.9
 37.5 25.8 37.8 22.4 48.9 26.6 27.2 23.5 28.3 44.2 25.4 22.2 30.5 26.5
 33.7 23.1 32.  29.9 23.9 28.5 26.4 20.2 33.6 38.6 39.2 27.7 31.4 36.5
 33.2 32.8 40.4 25.3 30.2 47.5 20.3 30.  28.9 28.1 31.1 21.7 27.  24.1
 45.9 44.1 22.9 29.1 32.3 41.1 25.6 29.8 26.3 26.2 29.4 24.4 28.  28.8
 34.6 19.4 30.3 41.5 22.6 56.6 27.1 31.3 31.  31.7 35.8 28.4 20.1 26.7
 38.7 34.9 25.  23.8 21.8 27.5 24.6 32.9 26.1 31.9 34.1 36.9 37.3 45.7
 34.2 23.6 22.3 37.1 45.  25.5 30.8 37.4 34.5 27.9 29.5 46.  42.5 35.5
 26.9 45.5 31.5 33.  23.4 30.7 20.5 21.5 40.  28.6 42.2 29.6 35.4 16.9
 26.8 39.3 32.6 35.9 21.2 42.4 40.5 36.7 29.3 19.6 18.  17.6 19.1 50.1
 17.7 54.6 35.  22.  39.4 19.7 22.5 25.2 41.8 60.9 23.7 24.5 31.2 16.
 31.6 25.1 24.8 18.3 20.  19.5 36.  35.3 40.1 43.1 21.4 34.3 27.6 16.5
 24.3 25.7 21.9 38.4 25.9 54.7 18.6 24.9 48.2 20.7 39.5 23.3 64.8 35.1
 43.6 21.  47.3 16.6 21.6 15.5 35.6 16.7 41.9 16.4 17.1 29.2 37.9 44.6
 39.6 40.3 41.6 39.  23.2 18.9 36.1 36.3 46.5 16.8 46.6 35.2 20.9 13.8
 31.8 15.3 38.2 45.2 17.  49.8 27.8 60.2 23.  22.1 26.  44.3 51.  39.7
 34.7 21.3 41.2 34.8 19.2 35.7 40.8 24.7 19.  32.4 34.  28.7 32.1 51.5
 20.4 30.6 71.9 19.3 40.9 17.2 16.1 16.2 40.6 18.4 21.1 42.3 32.2 50.2
 17.5 18.7 42.1 47.8 20.8 30.1 17.3 36.4 12.  36.2 55.7 14.4 43.  41.7
 33.8 43.9 22.7 57.5 37.  38.5 16.3 44.  32.7 54.2 40.2 33.3 17.4 41.3
 52.3 14.6 17.8 46.1 33.1 18.1 43.8 50.3 38.9 43.7 39.9 15.9 19.8 12.3
 78.  38.3 41.  42.6 43.4 15.1 20.6 33.5 43.2 30.4 38.  33.4 44.9 44.7
 37.6 39.8 53.4 55.2 42.  37.2 42.8 18.8 42.9 14.3 37.7 48.4 50.6 46.2
 49.5 43.3 33.9 18.5 44.5 45.4 55.  54.8 19.9 17.9 15.6 52.8 15.2 66.8
 55.1 18.2 48.5 55.9 57.3 10.3 14.1 15.7 56.  44.8 13.4 51.8 38.1 57.7
 44.4 38.8 49.3 39.1 54.  56.1 97.6 53.9 13.7 11.5 41.4 14.2 49.4 15.4
 45.1 49.2 48.7 53.8 42.7 48.8 52.7 53.5 50.5 15.8 45.3 14.8 51.9 63.3
 40.7 61.2 48.  46.8 48.3 58.1 50.4 11.3 12.8 13.5 14.5 15.  59.7 47.4
 52.5 13.2 52.9 61.6 49.9 54.3 47.9 13.  13.9 50.9 57.2 64.4 92.  50.8
 57.9 45.8 47.6 14.  46.4 46.9 47.1 13.3 48.1 51.7 46.3 54.1 14.9]
smoking_status values: <StringArray>
['formerly smoked', 'never smoked', 'smokes', 'Unknown']
Length: 4, dtype: str
stroke values: [1 0]

### Adjusting column types

In [219]:
df["age"] = df["age"].astype("uint8")
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

### Checking for NaN values

We check if there are any values missing from the dataset.
- `df.isna()` – returns a DataFrame of True/False values (True if the value in the original DataFrame is NaN, False otherwise)  
- `df.isna().any()` – for each column, checks if it contains at least one True value  
- `df.isna().any().any()` – returns True if there is **at least one NaN** in the original DataFrame, False otherwise

In [220]:
df.isna().any().any()

np.True_

### Dealing with NaNs

BMI is the only columns with missing values. We fill them using the gender average.

In [221]:
df["bmi"] = df["bmi"].fillna(df.groupby("gender")["bmi"].transform("mean"))
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,51676,Female,61,0,0,Yes,Self-employed,Rural,202.21,29.065758,never smoked,1
2,31112,Male,80,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,60182,Female,49,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,1665,Female,79,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80,1,0,Yes,Private,Urban,83.75,29.065758,never smoked,0
5106,44873,Female,81,0,0,Yes,Self-employed,Urban,125.20,40.000000,never smoked,0
5107,19723,Female,35,0,0,Yes,Self-employed,Rural,82.99,30.600000,never smoked,0
5108,37544,Male,51,0,0,Yes,Private,Rural,166.29,25.600000,formerly smoked,0
5109,44679,Female,44,0,0,Yes,Govt_job,Urban,85.28,26.200000,Unknown,0

### Modifying the data

In [222]:
# Binary to 1/0
df["ever_married"] = df["ever_married"].map({"Yes": 1, "No": 0})

# One-Hot Encoding
df = pd.get_dummies(df, columns=["gender", "work_type", "Residence_type", "smoking_status"])

# Convert all bool columns from OHE to int
bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)

df.head()

,id,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,stroke,gender_Female,gender_Male,...,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
0,9046,67,0,1,1,228.69,36.600000,1,0,1,...,0,1,0,0,0,1,0,1,0,0
1,51676,61,0,0,1,202.21,29.065758,1,1,0,...,0,0,1,0,1,0,0,0,1,0
2,31112,80,0,1,1,105.92,32.500000,1,0,1,...,0,1,0,0,1,0,0,0,1,0
3,60182,49,0,0,1,171.23,34.400000,1,1,0,...,0,1,0,0,0,1,0,0,0,1
4,1665,79,1,0,1,174.12,24.000000,1,1,0,...,0,0,1,0,1,0,0,0,1,0

In [223]:
# Move label to the rightmost side of the dataframe
cols = [c for c in df.columns if c != "stroke"] + ["stroke"]
df = df[cols]

### Renaming the columns

In this step we standardize the naming convention of features in the dataframe.

In [224]:
def get_renamed_column(name):
    name = name.strip()
    name = name.lower()
    name = name.replace(" ", "_")

    return name


def get_rename_dict(column_names):
    rename_dict = {}
    for name in column_names:
        rename_dict[name] = get_renamed_column(name)

    return rename_dict

In [225]:
df = df.rename(columns=get_rename_dict(df.columns))
df.head()

,id,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,gender_female,gender_male,gender_other,...,work_type_private,work_type_self-employed,work_type_children,residence_type_rural,residence_type_urban,smoking_status_unknown,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes,stroke
0,9046,67,0,1,1,228.69,36.600000,0,1,0,...,1,0,0,0,1,0,1,0,0,1
1,51676,61,0,0,1,202.21,29.065758,1,0,0,...,0,1,0,1,0,0,0,1,0,1
2,31112,80,0,1,1,105.92,32.500000,0,1,0,...,1,0,0,1,0,0,0,1,0,1
3,60182,49,0,0,1,171.23,34.400000,1,0,0,...,1,0,0,0,1,0,0,0,1,1
4,1665,79,1,0,1,174.12,24.000000,1,0,0,...,0,1,0,1,0,0,0,1,0,1

### Check for duplicates

In [226]:
any(df.duplicated())

False

There are only unique records in the dataset already, we may proceed.

### Check for class imbalance

Ideally here should be a similar number of records in each class.

In [227]:
df[df.columns[-1]].sum() / df[df.columns[-1]].size

np.float64(0.0487279843444227)

Since stroke was confirmed only in 5% of patients we will use SMOTE to create synthetic data and deal with the imbalance.

## Preparing the train and test sets

### Train-test split

In [228]:
columns_to_drop = []
df = df.drop(columns=columns_to_drop)

In [229]:
X = df.drop(columns=[df.columns[-1]]) 
y = df[df.columns[-1]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Create models

### Random Forests

In [230]:
random_forest_models = {
    "RandomForest_100_5": RandomForestClassifier(
        n_estimators=100,
        max_depth=5
    ),
    "RandomForest_50_5": RandomForestClassifier(
        n_estimators=50,
        max_depth=5
    ),
    "RandomForest_50_10": RandomForestClassifier(
        n_estimators=50,
        max_depth=10
    ),
    "RandomForest_500_3": RandomForestClassifier(
        n_estimators=500,
        max_depth=3
    ),
    "RandomForest_200_10": RandomForestClassifier(
        n_estimators=200,
        max_depth=10
    ),
    "RandomForest_300_7": RandomForestClassifier(
        n_estimators=300,
        max_depth=7
    ),
}

### Neural Networks

In [231]:
input_shape = X_train.shape[1]

neural_networks_models = {
    "NN_64_32_1": Sequential([
        Dense(64, activation="relu", input_shape=(input_shape,)),
        Dense(32, activation="relu"),
        Dense(1, activation="sigmoid")
    ]),
    "NN_32_32_32_1": Sequential([
        Dense(32, activation="sigmoid", input_shape=(input_shape,)),
        Dense(32, activation="sigmoid"),
        Dense(32, activation="sigmoid"),
        Dense(1, activation="sigmoid")
    ]),
    "NN_64_64_1": Sequential([
        Dense(64, activation="relu", input_shape=(input_shape,)),
        Dense(64, activation="tanh"),
        Dense(1, activation="sigmoid")
    ]),
    "NN_128_64_64_1": Sequential([
        Dense(128, activation="relu", input_shape=(input_shape,)),
        Dense(64, activation="relu"),
        Dense(64, activation="relu"),
        Dense(1, activation="sigmoid")
    ]),
    "NN_64_1": Sequential([
        Dense(64, activation="relu", input_shape=(input_shape,)),
        Dense(1, activation="sigmoid")
    ]),
    "NN_64_32_64_1": Sequential([
        Dense(64, activation="relu", input_shape=(input_shape,)),
        Dense(32, activation="tanh"),
        Dense(64, activation="tanh"),
        Dense(1, activation="sigmoid")
    ]),
}

c:\Users\Dell\anaconda\envs\tensorflow\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

## Train models

### Using SMOTE to deal with class imbalance

#### Cross-validation pipeline

In [232]:
def validate_models_smote(models, X, y):
    results = {}

    for name, model in models.items():
        pipeline = Pipeline([
            ("scaler", StandardScaler()),
            ("smote", SMOTE(sampling_strategy="minority")),
            ("model", model)
        ])

        scores = cross_validate(pipeline, X, y, cv=5, scoring=["precision", "recall", "f1"])
        results[name] = {
            "precision": scores["test_precision"].mean(),
            "recall": scores["test_recall"].mean(),
            "f1": scores["test_f1"].mean(),
        }

    return results

In [233]:
results = validate_models_smote(random_forest_models, X_train, y_train)
for name, result in results.items():
    print(f"{name}: {result}\n")

RandomForest_100_5: {'precision': np.float64(0.11280421870633614), 'recall': np.float64(0.7008534850640114), 'f1': np.float64(0.19429482932235378)}

RandomForest_50_5: {'precision': np.float64(0.1135619686757896), 'recall': np.float64(0.684352773826458), 'f1': np.float64(0.19468812702301216)}

RandomForest_50_10: {'precision': np.float64(0.12772165856036824), 'recall': np.float64(0.3524893314366999), 'f1': np.float64(0.18707544427246053)}

RandomForest_500_3: {'precision': np.float64(0.1157790763760352), 'recall': np.float64(0.7916073968705548), 'f1': np.float64(0.2019729990296141)}

RandomForest_200_10: {'precision': np.float64(0.124929861096673), 'recall': np.float64(0.3365576102418208), 'f1': np.float64(0.18156709836309337)}

RandomForest_300_7: {'precision': np.float64(0.125334066779431), 'recall': np.float64(0.5881934566145093), 'f1': np.float64(0.2063284823793093)}

#### Training pipeline

In [234]:
def train_models_smote(models, X, y):

    trained_models = {}

    for name, model in models.items():
        pipeline = Pipeline([
            ("scaler", StandardScaler()),
            ("smote", SMOTE(sampling_strategy="minority")),
            ("model", model)
        ])

        trained_pipeline = pipeline.fit(X, y)
        trained_models[name] = trained_pipeline

    return trained_models

In [235]:
trained_models = train_models_smote(random_forest_models, X_train, y_train)

for name, model in trained_models.items():
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)

    print(f"{name} Accuracy: {accuracy}")
    print(f"{name} Precision: {precision}")
    print(f"{name} Recall: {recall}\n")

RandomForest_100_5 Accuracy: 0.7348336594911937
RandomForest_100_5 Precision: 0.15737704918032788
RandomForest_100_5 Recall: 0.7741935483870968

RandomForest_50_5 Accuracy: 0.7172211350293543
RandomForest_50_5 Precision: 0.15076923076923077
RandomForest_50_5 Recall: 0.7903225806451613

RandomForest_50_10 Accuracy: 0.8317025440313112
RandomForest_50_10 Precision: 0.17647058823529413
RandomForest_50_10 Recall: 0.4838709677419355

RandomForest_500_3 Accuracy: 0.7123287671232876
RandomForest_500_3 Precision: 0.15269461077844312
RandomForest_500_3 Recall: 0.8225806451612904

RandomForest_200_10 Accuracy: 0.8287671232876712
RandomForest_200_10 Precision: 0.15757575757575756
RandomForest_200_10 Recall: 0.41935483870967744

RandomForest_300_7 Accuracy: 0.7710371819960861
RandomForest_300_7 Precision: 0.16666666666666666
RandomForest_300_7 Recall: 0.6935483870967742

### Using Ensemble to deal with class imbalance

#### Cross-validation pipeline

#### Training pipeline

### Using class weight to deal with the imbalance

#### Training Neural Networks

In [240]:
def train_neural_networks(models, X, y):
    results = {}

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    for name, model in models.items():
        model_copy = clone_model(model)
        model_copy.set_weights(model.get_weights()) 
        
        model_copy.compile(optimizer=Adam(learning_rate=0.001), loss="binary_crossentropy", metrics=["precision", "recall"])
        model_copy.fit(X_scaled, y, epochs=50, batch_size=32, verbose=0, class_weight={0: 1, 1: 19}, validation_split=0.2)

        results[name] = model_copy

    return results, scaler

In [243]:
trained_models, scaler = train_neural_networks(neural_networks_models, X_train, y_train)
X_test_scaled = scaler.transform(X_test)

for name, model in trained_models.items():
    y_prob = model.predict(X_test_scaled).flatten()
    for threshold in [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]:
        print(f"CURRENT THRESHOLD: {threshold}")
        y_pred = (y_prob > threshold).astype(int) 

        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)

        print(f"{name} Accuracy: {accuracy}")
        print(f"{name} Precision: {precision}")
        print(f"{name} Recall: {recall}\n")

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
CURRENT THRESHOLD: 0.1
NN_64_32_1 Accuracy: 0.6800391389432485
NN_64_32_1 Precision: 0.136986301369863
NN_64_32_1 Recall: 0.8064516129032258

CURRENT THRESHOLD: 0.2
NN_64_32_1 Accuracy: 0.7309197651663405
NN_64_32_1 Precision: 0.14381270903010032
NN_64_32_1 Recall: 0.6935483870967742

CURRENT THRESHOLD: 0.3
NN_64_32_1 Accuracy: 0.7514677103718199
NN_64_32_1 Precision: 0.13358778625954199
NN_64_32_1 Recall: 0.5645161290322581

CURRENT THRESHOLD: 0.4
NN_64_32_1 Accuracy: 0.786692759295499
NN_64_32_1 Precision: 0.14545454545454545
NN_64_32_1 Recall: 0.5161290322580645

CURRENT THRESHOLD: 0.5
NN_64_32_1 Accuracy: 0.8131115459882583
NN_64_32_1 Precision: 0.14754098360655737
NN_64_32_1 Recall: 0.43548387096774194

CURRENT THRESHOLD: 0.6
NN_64_32_1 Accuracy: 0.8395303326810176
NN_64_32_1 Precision: 0.16
NN_64_32_1 Recall: 0.3870967741935484

CURRENT THRESHOLD: 0.7
NN_64_32_1 Accuracy: 0.8581213307240705
NN_64_32_1 Precision: 0.15126050420168066
NN_64_32_1 Recall: 0.2903225806451613

CURRENT THRESHOLD: 0.8
NN_64_32_1 Accuracy: 0.8825831702544031
NN_64_32_1 Precision: 0.14634146341463414
NN_64_32_1 Recall: 0.1935483870967742

CURRENT THRESHOLD: 0.9
NN_64_32_1 Accuracy: 0.9197651663405088
NN_64_32_1 Precision: 0.20588235294117646
NN_64_32_1 Recall: 0.11290322580645161

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
CURRENT THRESHOLD: 0.1
NN_32_32_32_1 Accuracy: 0.45792563600782776
NN_32_32_32_1 Precision: 0.10064935064935066
NN_32_32_32_1 Recall: 1.0

CURRENT THRESHOLD: 0.2
NN_32_32_32_1 Accuracy: 0.5567514677103719
NN_32_32_32_1 Precision: 0.11287128712871287
NN_32_32_32_1 Recall: 0.9193548387096774

CURRENT THRESHOLD: 0.3
NN_32_32_32_1 Accuracy: 0.6477495107632094
NN_32_32_32_1 Precision: 0.1383495145631068
NN_32_32_32_1 Recall: 0.9193548387096774

CURRENT THRESHOLD: 0.4
NN_32_32_32_1 Accuracy: 0.7093933463796478
NN_32_32_32_1 Precision: 0.15743440233236153
NN_32_32_32_1 Recall: 0.8709677419354839

CURRENT THRESHOLD: 0.5
NN_32_32_32_1 Accuracy: 0.7622309197651663
NN_32_32_32_1 Precision: 0.16605166051660517
NN_32_32_32_1 Recall: 0.7258064516129032

CURRENT THRESHOLD: 0.6
NN_32_32_32_1 Accuracy: 0.8189823874755382
NN_32_32_32_1 Precision: 0.19095477386934673
NN_32_32_32_1 Recall: 0.6129032258064516

CURRENT THRESHOLD: 0.7
NN_32_32_32_1 Accuracy: 0.8679060665362035
NN_32_32_32_1 Precision: 0.23741007194244604
NN_32_32_32_1 Recall: 0.532258064516129

CURRENT THRESHOLD: 0.8
NN_32_32_32_1 Accuracy: 0.9305283757338552
NN_32_32_32_1 Precision: 0.3783783783783784
NN_32_32_32_1 Recall: 0.22580645161290322

CURRENT THRESHOLD: 0.9
NN_32_32_32_1 Accuracy: 0.9393346379647749
NN_32_32_32_1 Precision: 0.0
NN_32_32_32_1 Recall: 0.0

c:\Users\Dell\anaconda\envs\tensorflow\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
CURRENT THRESHOLD: 0.1
NN_64_64_1 Accuracy: 0.6643835616438356
NN_64_64_1 Precision: 0.1273209549071618
NN_64_64_1 Recall: 0.7741935483870968

CURRENT THRESHOLD: 0.2
NN_64_64_1 Accuracy: 0.7270058708414873
NN_64_64_1 Precision: 0.13712374581939799
NN_64_64_1 Recall: 0.6612903225806451

CURRENT THRESHOLD: 0.3
NN_64_64_1 Accuracy: 0.7661448140900196
NN_64_64_1 Precision: 0.14741035856573706
NN_64_64_1 Recall: 0.5967741935483871

CURRENT THRESHOLD: 0.4
NN_64_64_1 Accuracy: 0.7906066536203522
NN_64_64_1 Precision: 0.15454545454545454
NN_64_64_1 Recall: 0.5483870967741935

CURRENT THRESHOLD: 0.5
NN_64_64_1 Accuracy: 0.8091976516634051
NN_64_64_1 Precision: 0.15897435897435896
NN_64_64_1 Recall: 0.5

CURRENT THRESHOLD: 0.6
NN_64_64_1 Accuracy: 0.8346379647749511
NN_64_64_1 Precision: 0.17575757575757575
NN_64_64_1 Recall: 0.46774193548387094

CURRENT THRESHOLD: 0.7
NN_64_64_1 Accuracy: 0.8542074363992173
NN_64_64_1 Precision: 0.18705035971223022
NN_64_64_1 Recall: 0.41935483870967744

CURRENT THRESHOLD: 0.8
NN_64_64_1 Accuracy: 0.8816046966731899
NN_64_64_1 Precision: 0.21359223300970873
NN_64_64_1 Recall: 0.3548387096774194

CURRENT THRESHOLD: 0.9
NN_64_64_1 Accuracy: 0.8992172211350293
NN_64_64_1 Precision: 0.16393442622950818
NN_64_64_1 Recall: 0.16129032258064516

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
CURRENT THRESHOLD: 0.1
NN_128_64_64_1 Accuracy: 0.8698630136986302
NN_128_64_64_1 Precision: 0.1485148514851485
NN_128_64_64_1 Recall: 0.24193548387096775

CURRENT THRESHOLD: 0.2
NN_128_64_64_1 Accuracy: 0.8933463796477495
NN_128_64_64_1 Precision: 0.18666666666666668
NN_128_64_64_1 Recall: 0.22580645161290322

CURRENT THRESHOLD: 0.3
NN_128_64_64_1 Accuracy: 0.8962818003913894
NN_128_64_64_1 Precision: 0.17647058823529413
NN_128_64_64_1 Recall: 0.1935483870967742

CURRENT THRESHOLD: 0.4
NN_128_64_64_1 Accuracy: 0.901174168297456
NN_128_64_64_1 Precision: 0.19047619047619047
NN_128_64_64_1 Recall: 0.1935483870967742

CURRENT THRESHOLD: 0.5
NN_128_64_64_1 Accuracy: 0.9080234833659491
NN_128_64_64_1 Precision: 0.19230769230769232
NN_128_64_64_1 Recall: 0.16129032258064516

CURRENT THRESHOLD: 0.6
NN_128_64_64_1 Accuracy: 0.9080234833659491
NN_128_64_64_1 Precision: 0.16666666666666666
NN_128_64_64_1 Recall: 0.12903225806451613

CURRENT THRESHOLD: 0.7
NN_128_64_64_1 Accuracy: 0.910958904109589
NN_128_64_64_1 Precision: 0.16279069767441862
NN_128_64_64_1 Recall: 0.11290322580645161

CURRENT THRESHOLD: 0.8
NN_128_64_64_1 Accuracy: 0.9119373776908023
NN_128_64_64_1 Precision: 0.13157894736842105
NN_128_64_64_1 Recall: 0.08064516129032258

CURRENT THRESHOLD: 0.9
NN_128_64_64_1 Accuracy: 0.9207436399217221
NN_128_64_64_1 Precision: 0.1724137931034483
NN_128_64_64_1 Recall: 0.08064516129032258

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
CURRENT THRESHOLD: 0.1
NN_64_1 Accuracy: 0.5283757338551859
NN_64_1 Precision: 0.10820895522388059
NN_64_1 Recall: 0.9354838709677419

CURRENT THRESHOLD: 0.2
NN_64_1 Accuracy: 0.6340508806262231
NN_64_1 Precision: 0.13033175355450238
NN_64_1 Recall: 0.8870967741935484

CURRENT THRESHOLD: 0.3
NN_64_1 Accuracy: 0.6986301369863014
NN_64_1 Precision: 0.13609467455621302
NN_64_1 Recall: 0.7419354838709677

CURRENT THRESHOLD: 0.4
NN_64_1 Accuracy: 0.7485322896281801
NN_64_1 Precision: 0.15302491103202848
NN_64_1 Recall: 0.6935483870967742

CURRENT THRESHOLD: 0.5
NN_64_1 Accuracy: 0.7945205479452054
NN_64_1 Precision: 0.16964285714285715
NN_64_1 Recall: 0.6129032258064516

CURRENT THRESHOLD: 0.6
NN_64_1 Accuracy: 0.8326810176125244
NN_64_1 Precision: 0.17365269461077845
NN_64_1 Recall: 0.46774193548387094

CURRENT THRESHOLD: 0.7
NN_64_1 Accuracy: 0.8639921722113503
NN_64_1 Precision: 0.1968503937007874
NN_64_1 Recall: 0.4032258064516129

CURRENT THRESHOLD: 0.8
NN_64_1 Accuracy: 0.9021526418786693
NN_64_1 Precision: 0.22857142857142856
NN_64_1 Recall: 0.25806451612903225

CURRENT THRESHOLD: 0.9
NN_64_1 Accuracy: 0.9246575342465754
NN_64_1 Precision: 0.14285714285714285
NN_64_1 Recall: 0.04838709677419355

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
CURRENT THRESHOLD: 0.1
NN_64_32_64_1 Accuracy: 0.7622309197651663
NN_64_32_64_1 Precision: 0.12448132780082988
NN_64_32_64_1 Recall: 0.4838709677419355

CURRENT THRESHOLD: 0.2
NN_64_32_64_1 Accuracy: 0.7935420743639922
NN_64_32_64_1 Precision: 0.11794871794871795
NN_64_32_64_1 Recall: 0.3709677419354839

CURRENT THRESHOLD: 0.3
NN_64_32_64_1 Accuracy: 0.8180039138943248
NN_64_32_64_1 Precision: 0.11728395061728394
NN_64_32_64_1 Recall: 0.3064516129032258

CURRENT THRESHOLD: 0.4
NN_64_32_64_1 Accuracy: 0.8346379647749511
NN_64_32_64_1 Precision: 0.1258741258741259
NN_64_32_64_1 Recall: 0.2903225806451613

CURRENT THRESHOLD: 0.5
NN_64_32_64_1 Accuracy: 0.8512720156555773
NN_64_32_64_1 Precision: 0.13709677419354838
NN_64_32_64_1 Recall: 0.27419354838709675

CURRENT THRESHOLD: 0.6
NN_64_32_64_1 Accuracy: 0.8649706457925636
NN_64_32_64_1 Precision: 0.14150943396226415
NN_64_32_64_1 Recall: 0.24193548387096775

CURRENT THRESHOLD: 0.7
NN_64_32_64_1 Accuracy: 0.8786692759295499
NN_64_32_64_1 Precision: 0.13095238095238096
NN_64_32_64_1 Recall: 0.1774193548387097

CURRENT THRESHOLD: 0.8
NN_64_32_64_1 Accuracy: 0.8953033268101761
NN_64_32_64_1 Precision: 0.10526315789473684
NN_64_32_64_1 Recall: 0.0967741935483871

CURRENT THRESHOLD: 0.9
NN_64_32_64_1 Accuracy: 0.9090019569471625
NN_64_32_64_1 Precision: 0.08108108108108109
NN_64_32_64_1 Recall: 0.04838709677419355